### ISSUE TITLE
Don't catch Throwable

### ISSUE THREAD

**Issue by ahill-shopatron** [mesos/chronos#124]
In several places throughout Chronos, there are `catch` constructs which respond to `java.lang.Throwable`. This is far too coarse-grained.

I remind you that `Throwable` has two direct subtypes: there is `Exception`, which represents problems which it may be possible to recover from. But there is also `Error`, which in general represents problems that cannot be recovered from.

The only generally-applicable response to an `Error` is for the application to commit honorable suicide and let its minder resurrect it once it's finished crashing. In fact, this is what happens if you simply don't catch the thing and let it unwind the stack all the way to the top level.

Catching `Exception` is odd, but defensible. Catching `Throwable` seems irresponsible, especially when the response is to merely log the thing and continue on oblivious to the potentially serious problem (as in MailClient.scala, for instance).

**Comment by elingg** [comment]
This appears to have been fixed some time ago.
