### ISSUE TITLE
Install Chronos in Linux mint 1.5 and issues collections

### ISSUE THREAD

**Issue by rocker96** [mesos/chronos#157]
Hi all, after one month learning and testing Chronos, I list the issues and installation experience as below:
<b>[issues]</b>
<b>1.</b> Can't refer to cpus/mem/disk/ports resources for each job. I think a "comment" field is also needed to describe what the job is.
My reason is: Sometimes we have a big program to run with all resources of one slave.
My solution: Add resources configuration in WebUI and scala code. ports resource is very importance for our requirement that some jobs should only run in one slave or several slaves we want.

<b>2.</b> Timezone issue in Chronos 1x & 2.01.
The default timeZone is "UTC". My timezone is "Asia/Shanghai", 8 hours different with UTC. It seems Chronos do not support different timezone.
My solution is 2 steps:
Step1: Change all the scala code to replace 
DateTimeZone.UTC
to
DateTimeZone.forID("Asia/Shanghai");

Step2: Modify JobScheduler.scala to minus 8 hours in function next();
final def next(now: DateTime ...)
...
    } else {
      val job = jobOption.get
      //****Add this line and change other nextDate to nextDate_AsiaTimeZone
      val nextDate_AsiaTimeZone = nextDate.minusHours(8)
      //****Add this line****
     if (nextDate_AsiaTimeZone.isAfter(now.minus(job.epsilon)) && nextDate_AsiaTimeZone.isBefore(now.plus(scheduleHorizon))) {
...

<b>3.</b> The issue someone ask "Chronos services only works with local mesos master". It seems a bug of mesos 0.14 and hope this can be fixed in 0.15

<b>[Installation experience]</b>
1. Linux server: Linux mint 1.5 mate version, run apt-get to install some software before installing mesos 0.14.1:
apt-get update && apt-get install maven python-dev libunwind8-dev libcppunit-dev openjdk-7-jdk autoconf autopoint libltdl-dev libtool autotools-dev make gawk g++ curl libcurl4-openssl-dev nodejs

2. Modify /mesos-0.14.1/src/files/files.cpp before running ./configure, or we will meet compile issue:
// Cap the read length at 16 pages.
length = std::min(length, (ssize_t) sysconf(_SC_PAGE_SIZE) * 16);

3. Modify build.xml of Chronos before mvn package:
1) If your node command is not "node", then change to "nodejs"
2) add <arg value="--stack-size=2048"/>, or you may build js failed.

4. Add repository in pom.xml of Chronos. In China, some package didn't find in the default repository.
http://repo1.maven.org/maven2/
http://maven.tempo-db.com/artifactory/list/twitter/

Then try to start building mesos and Chronos.

**Comment by elingg** [comment]
Closing this issue as out of date, please reopen if you are still encountering this error with the latest version of Mesos.
