### ISSUE TITLE
to build mesos on aws linux boxes, need to use  --enable-frame-pointers

### ISSUE THREAD

**Issue by andrewglenn** [mesos/chronos#160]
Hi there,

It looks like the standard aws ec2 linux box dies during the make step for building mesos.  

To fix it, the .configure instructions need to be updated to:

```
configure --with-webui --with-included-zookeeper --disable-perftools  --enable-frame-pointers
```

If you agree, you may wish to update the aws section accordingly.

cheers,
Andrew

**Comment by elingg** [comment]
Closing this out of date issue that was already merged.
