### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by kentnc** [mesos/chronos#162]
Not sure what I am doing wrong.  my output from `mvn -X clean package` was too long.

[kent@kn-fedora airbnb-chronos-3bb0ce7]$ bin/installer.bash
Welcome to the interactive chronos installation. This script will first install mesos and then chronos.

Depending on your hardware and internet connection, this script might take 15 - 25 minutes as we're compiling mesos from source.
If you run into any issues, please check the FAQ in the chronos repo.
Do you have mesos installed already? Type 'yes' or 'no' followed by [ENTER]:
yes
Type the path of the compiled mesos installation followed by [ENTER]:
/home/kent/chronos/mesos-0.14.1
Skipping mesos installation
~/chronos/mesos-0.14.1 ~/chronos/airbnb-chronos-3bb0ce7
Installing snapshot of mesos version 0.14.1 into local mvn repository
Error: JAVA_HOME is not defined correctly.
  We cannot execute /home/kent/chronos/jvm/java-1.7.0-openjdk-1.7.0.9/bin/java
[kent@kn-fedora airbnb-chronos-3bb0ce7]$ export JAVA_HOME=/home/kent/chronos/jvm/java-1.7.0-openjdk-1.7.0.9/jre
[kent@kn-fedora airbnb-chronos-3bb0ce7]$ bin/installer.bash
Welcome to the interactive chronos installation. This script will first install mesos and then chronos.

Depending on your hardware and internet connection, this script might take 15 - 25 minutes as we're compiling mesos from source.
If you run into any issues, please check the FAQ in the chronos repo.
Do you have mesos installed already? Type 'yes' or 'no' followed by [ENTER]:
yes
Type the path of the compiled mesos installation followed by [ENTER]:
/home/kent/chronos/mesos-0.14.1
Skipping mesos installation
~/chronos/mesos-0.14.1 ~/chronos/airbnb-chronos-3bb0ce7
Installing snapshot of mesos version 0.14.1 into local mvn repository
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ standalone-pom ---
[INFO] Installing /home/kent/chronos/mesos-0.14.1/src/mesos-0.14.1.jar to /home/kent/.m2/repository/org/apache/mesos/mesos/0.14.1-SNAPSHOT/mesos-0.14.1-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.490s
[INFO] Finished at: Thu Nov 21 14:06:01 EST 2013
[INFO] Final Memory: 5M/15M
[INFO] ------------------------------------------------------------------------
Replacing pom.xml mesos dependency
~/chronos/airbnb-chronos-3bb0ce7
~/chronos/airbnb-chronos-3bb0ce7/bin ~/chronos/airbnb-chronos-3bb0ce7
Installing chronos
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building chronos 2.0.1_mesos-0.14.0-rc4
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (ant-run-requirejs) @ chronos ---
[INFO] Executing tasks

main:

sourceDir.check:

assets.uptodate:

generateAssets:
     [echo] Combining and minifying JS files.

-optimize:
     [exec] axconfig: unable to open axports file /etc/ax25/axports (No such file or directory)
     [exec] Result: 1
     [echo] optimized /home/kent/chronos/airbnb-chronos-3bb0ce7/src/main/resources/assets/app.build.js with node
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ chronos ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/kent/chronos/airbnb-chronos-3bb0ce7/src/main/resources/assets/build
[INFO] 
[INFO] --- scala-maven-plugin:3.1.0:add-source (scala-compile-first) @ chronos ---
[INFO] Add Source directory: /home/kent/chronos/airbnb-chronos-3bb0ce7/src/main/scala
[INFO] Add Test Source directory: /home/kent/chronos/airbnb-chronos-3bb0ce7/src/test/scala
[INFO] 
[INFO] --- scala-maven-plugin:3.1.0:compile (scala-compile-first) @ chronos ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.3
[WARNING]  com.airbnb:chronos:2.0.1_mesos-0.14.0-rc4 requires scala version: 2.10.3
[WARNING]  mesosphere:chaos:0.4.5 requires scala version: 2.10.2
[WARNING] Multiple versions of scala libraries detected!
[INFO] /home/kent/chronos/airbnb-chronos-3bb0ce7/src/main/scala:-1: info: compiling
[INFO] Compiling 38 source files to /home/kent/chronos/airbnb-chronos-3bb0ce7/target/classes at 1385060766609
[ERROR] Error occurred during initialization of VM
[INFO] Could not reserve enough space for object heap
[ERROR] Error: Could not create the Java Virtual Machine.
[ERROR] Error: A fatal exception has occurred. Program will exit.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.790s
[INFO] Finished at: Thu Nov 21 14:06:06 EST 2013
[INFO] Final Memory: 12M/30M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.0:compile (scala-compile-first) on project chronos: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1(Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[kent@kn-fedora airbnb-chronos-3bb0ce7]$ env | grep JAVA
JAVA_OPTIONS=-Xms512m
JAVA_OPTS=-Xms512m
JAVA_HOME=/home/kent/chronos/jvm/java-1.7.0-openjdk-1.7.0.9/jre
JAVA_HEADERS=
[kent@kn-fedora airbnb-chronos-3bb0ce7]$ java -version
java version "1.7.0_09-icedtea"
OpenJDK Runtime Environment (fedora-2.3.5.3.fc16-i386)
OpenJDK Client VM (build 23.2-b09, mixed mode)
[kent@kn-fedora airbnb-chronos-3bb0ce7]$

**Comment by elingg** [comment]
Closing this out of date issue
