### ISSUE TITLE
Shared auth with Marathon

### ISSUE THREAD

**Issue by benmccann** [mesos/chronos#190]
There's a large overlap in users of Marathon and Chronos. It'd reduce operational complexity for everyone using both if we could find a way to work with Marathon to have shared auth. Benefits of having just one place to store credentials include making it easier to manage when an employee joins or leaves the company, easier password changes, easier to create auth plugins (e.g. I thought it might be interesting to implement SAML support so mesos could be used with OneLogin and similar services) This could be a shared library that both use, merging the code bases, or some other solution. Both projects have many of the same users and same committers (e.g. @ssorallen and @florianleibert are top committers of both), so I think this could be feasible. I'm not involved in either project and realize the difficulties of coordinating across projects, but it could be interesting to discuss. I've opened this issue on the Marathon project as well (https://github.com/mesosphere/marathon/issues/168)

**Comment by gkleiman** [comment]
Including @guenter's response in mesosphere/marathon#168:

> Thanks for the suggestions @benmccann. We'd like to follow the UNIX model of small programs that do one thing really well and there are no plans to merge the codebases.
>
>A solution for unified authentication should rely on an authentication protocol that enables this (e.g. LDAP or OAuth). It's not necessary to merge the codebases to do this.

**Comment by benmccann** [comment]
I agree. I wasn't suggesting merging codebases. Just implementing support for LDAP, OAuth, SAML, etc. in a shared library that both can use.
