### ISSUE TITLE
how to specify a slave name when scheduling a job on chronos

### ISSUE THREAD

**Issue by CruncherBigData** [mesos/chronos#196]
Hello all, 
I have a Chronos server with multiple nodes, only one node/slave contains all the required dependencies to run my job, how do I tell Chonos to run a job on a specific node/slave ?

thanks in advance.

**Comment by chengweiv5** [comment]
For anyone interested in the feature of filter nodes with attribute, so far, we hasn't been start this feature yet and may not start to work on this in a short feature, if you're interested to work on it, please take over.

**Comment by kapil-malik** [comment]
https://mesos.github.io/chronos/docs/api.html#constraints seems to serve what @chengweiv5 mentioned. We are using this feature and it works pretty well. I think this issue may be closed.

**Comment by altoplano** [comment]
Could you describe how you use this - tried to use ["hostname", "LIKE", "app0*"] where a similar construct works for our Marathon jobs and didn't seem to work - would show up as scheduled, but never actually run.
Not being a Scala person my read of the code didn't get me far, but it looked to only support "CLUSTER" so I was confused...
Any help appreciated.
