### ISSUE TITLE
Force the execution of a task on a specific node

### ISSUE THREAD

**Issue by romain-nio** [mesos/chronos#210]
Hi,

I see this very interesting request on the googlegroup : https://groups.google.com/forum/#!topic/chronos-scheduler/Q-7IssDW84w

I'm looking forward having it too :)

I have a master zk and mesos installed on "master" host. One mesos slave on "slave1" and "slave2". Basically, I want to execute tasks ONLY on a spefic node, for example execute job "foo" on the node "slave1".

Thank you so much :)

**Comment by elingg** [comment]
Closing as duplicate
