### ISSUE TITLE
Spaces in job name causes failure

### ISSUE THREAD

**Issue by devoncrouse** [mesos/chronos#215]
Ubuntu 13.10, Mesos 0.18, Chronos master.

A job named "Job with spaces" with command "sleep 1" fails with the following stderr:

```bash
/usr/bin/env: with: No such file or directory
```

The same command in a job named "Job_without_spaces" succeeds. Looks like the spaces need to be escaped (or constraints placed on the job name in the UI).

**Comment by elingg** [comment]
Also can't reproduce this issue, it appears to be fixed. Please reopen if you are still encountering it.
