### ISSUE TITLE
Keep a Job Run History and make available via API

### ISSUE THREAD

**Issue by gmalouf** [mesos/chronos#224]
We use Chronos to import reporting data from a third party system for specific time intervals.  Something that would be really cool is to be able to see for each execution:

- Timestamp/Datetime of execution
- Whether this was an initial run, a retry or manual kickoff
- Did the job succeed/fail
- How long did it run for? 

Bonus would be a link to the output from that job execution, but that can be complicated with Mesos.

**Comment by logikal** [comment]
Old request, but still +1.

**Comment by scaldmaster** [comment]
+1

**Comment by laktech** [comment]
+1

**Comment by elingg** [comment]
We added this recently through the job stats. @brndnmtthws, are we safe to close this?

**Comment by laktech** [comment]
@elingg would it be possible to include a link to the new functionality? seems like a few people were waiting for this feature. PR or docs or something.

**Comment by elingg** [comment]
Certainly, https://github.com/mesos/chronos/pull/402.
