### ISSUE TITLE
Chronos doesn't register with Mesos

### ISSUE THREAD

**Issue by niiamon** [mesos/chronos#226]
Hi.

I am trying to setup Chronos and I can't seem to be able to tell if the Chronos framework has registered with the Mesos master. I am using Vagrant boxes for Zookeeper, Mesos and Marathon found here:

`https://github.com/everpeace/vagrant-mesos`

When I up the cluster, I am able to see Mesos and Marathon UI and I can see that Marathon has registered as a framework with Mesos. I can create jobs on Marathon and see them execute. 

However, when I run Chronos with this command:

`./bin/start-chronos.bash --master zk://172.31.1.11:5050/mesos --zk_hosts zk://172.31.0.11:2181/mesos --http_port 8082`

I do not see anywhere in the logs that Chronos is attempting to register with Mesos and Chronos is not showing up in the Frameworks for Mesos on the Mesos UI. 

Furthermore, if I start only one Chronos instance, it keeps spitting out this error: 

`2014-06-09 13:56:03,727:46453(0x133087000):ZOO_ERROR@handle_socket_error_msg@1603: Socket [172.31.1.11:5050] zk retcode=-4, errno=64(Host is down): failed while receiving a server response`

But when I start another Chronos instance, the new instance doesn't show that error. So it appears that in order to get one Chronos working properly, I need to run two Chronos instances? Thoroughly confused.

**Comment by brandongalbraith** [comment]
@niiamon Did the change @tsunokawa recommend solve this for you?

**Comment by elingg** [comment]
Did this solution work? Closing this out of date issue, but reopen if there is still a problem. Thanks!
