### ISSUE TITLE
Chronos with Symfony2

### ISSUE THREAD

**Issue by FHMSolutions** [mesos/chronos#231]
Hi all,

I have an issue with my chronos. Chronos calls a command from Symfony which calls a Symfony's service. But it returns an error "file get content is empty".

When i remove the Symfony's service, i have a job success. Otherwise i have job failure.

Anyone can help me ?

**Comment by andygrunwald** [comment]
Hey,

we are running Chronos with Symfony Console. And it works very well.
I want to help you, but your issue contains to less information.

Can you please post your Job definition and an example source code?
The Mesos + Chronos Version as well, please
Maybe this can help.

**Comment by gomes** [comment]
Hey, I think it is not a problem anymore, 1 year after it can be closed, right?

**Comment by FHMSolutions** [comment]
Hello,

Yes, the issue can be closed !

2015-10-02 0:04 GMT+02:00 Diogo Gomes <notifications@github.com>:
