### ISSUE TITLE
Unable to add a 'Dependent' job via command line

### ISSUE THREAD

**Issue by panwaria** [mesos/chronos#239]
Hi,

I've been successfully running Chronos on my machine. I'm able to add and schedule dependent jobs using the Chronos web UI. But, I'm not able to add a 'dependent job' on the Chronos scheduler using command line. 

I'm using the following command (as mentioned in the airbnb github page as well):

curl -L -X POST -H 'Content-Type: application/json' -d '{
        "name" : "child_task_01",
        "executor" : "/usr/bin/etl_script.sh",
        "owner" : "prakhar.panwaria9@gmail.com",
        "command" : "ls",
        "epsilon" : "PT15M",
        "parents" : ["parent_task_01"]
}' localhost:8081/scheduler/iso8601

And, I'm getting following error:

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 Server Error</title>
</head>
<body>

<h2>HTTP ERROR: 500</h2>

<p>Problem accessing /scheduler/iso8601. Reason:
<pre>    Server Error</pre></p>

<hr /><i><small>Powered by Jetty://</small></i>

But, if I replace 'parents' field by 'schedule' (i.e., make this child_task_01 as an independent schedule based job), it gets added to the Chronos scheduler successfully.

Does anyone have a clue what I might be missing here?

Thanks,
prakhar

**Comment by kkdevops** [comment]
please include on offitial chronos docs
