### ISSUE TITLE
Chronos UI extremely sluggish after adding large number of jobs.

### ISSUE THREAD

**Issue by panwaria** [mesos/chronos#294]
Hi,

Chronos UI seems to be getting sluggish after I added a large number of jobs (>370 now). I guess it's because Chronos is trying to ping Zookeeper and get latest information every 3-5 seconds. If that's the case, is there a way to increase that time duration? Or is there something else which might be causing this?

Thanks in advance!

**Comment by adamcsanders** [comment]
Is there any way to re-open this issue? The UI is legitimately sluggish after you add a hundred or so jobs, and it becomes barely useable after around 300 jobs.

**Comment by panwaria** [comment]
It'll be great if this issue gets fixed sooner or later.

**Comment by mwilbz** [comment]
This may no longer be an issue in newer versions of Chronos, but we're using a fork of 2.4.0 and were able to improve performance on the UI by removing the `buildGraph()` method in job_graph.js. The method was inefficiently constructing a job graph in the browser, and apparently wasn't being used anywhere.
