### ISSUE TITLE
Document of the format of Run Interval

### ISSUE THREAD

**Issue by dhobbs** [mesos/chronos#313]
This page: https://github.com/airbnb/chronos#adding-a-scheduled-job goes into some good detail (yay!) describing ISO8601 time formats, but has a single bullet point for 'the run interval' with no details at all.

It appears that it always starts 'PT' followed by a number and a letter. Can more detail be added please? Is it always prefixed with PT? What does PT stand for? What are some examples of valid run intervals?

Many thanks!

**Comment by elingg** [comment]
Closed since this PR was merged
