### ISSUE TITLE
Chronos launch Docker task

### ISSUE THREAD

**Issue by sourav82** [mesos/chronos#331]
Could you please let me know how to launch a Docker task using Chronos WebUI?

Any example will suffice.

Thanks & Regards,
Sourav

**Comment by whua-airbnb** [comment]
I do not know, but will do some research.

发自我的 iPhone

在 Dec 31, 2014，12:53 AM，sourav82 <notifications@github.com> 写道：

**Comment by chengweiv5** [comment]
check out this https://github.com/relateiq/mesos-docker

**Comment by offlinehacker** [comment]
It's currently not possible see: https://github.com/airbnb/chronos/issues/314
