### ISSUE TITLE
Please document configuration options

### ISSUE THREAD

**Issue by mindscratch** [mesos/chronos#336]
According to the [CONFIG](https://github.com/airbnb/chronos/blob/master/docs/CONFIG.md) page, I should run "start-chronos.bash --config" to see what configuration options are available. However, I've installed the chronos RPM on CentOS and that bash script doesn't exist.

If I run `/usr/local/bin/chronos --help` I get:

```
USAGE: chronos-framework (--jar <chronos.jar>)? <option>*

...
```

The other text in the help says to configure chronos by using /etc/chronos/conf or passing command-line arguments, which of course I don't know.

**Comment by juicedM3** [comment]
Looking through the source, 

<code>$ grep opt src/main/scala/org/apache/mesos/chronos/scheduler/config/SchedulerConfiguration.scala | cut -d'"' -f2 | sort</code>

here are the available options:

<pre>
cluster_name
disable_after_failures
failover_timeout
failure_retry
hostname
leader_max_idle_time
mail_from
mail_password
mail_server
mail_ssl
mail_user
master
mesos_checkpoint
mesos_framework_name
mesos_role
mesos_task_cpu
mesos_task_disk
mesos_task_mem
raven_dsn
reconciliation_interval
schedule_horizon
slack_channel
slack_token
slack_url
task_epsilon
user
zk_hosts
zk_path
zk_timeout
</pre>

**Comment by simonvc** [comment]
+1

**Comment by modeyang** [comment]
+1

**Comment by msiebeneicher** [comment]
+1

**Comment by BrianHicks** [comment]
+1

**Comment by ryane** [comment]
+1

**Comment by flyinprogrammer** [comment]
```
/usr/bin/chronos run_jar --help
```

Is what you want probably?

**Comment by samklr** [comment]
+1

**Comment by gkleiman** [comment]
The configuration flags have been added to the `configuration.md` file.

The documentation site will be updated once we release the next version.
