### ISSUE TITLE
ERROR org.apache.zookeeper.server.NIOServerCnxn: Thread Thread[main,5,main] died

### ISSUE THREAD

**Issue by ronaldgames** [mesos/chronos#34]
When start chronos:

INFO  [2013-05-06 13:52:00,545] org.apache.zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:28281
INFO  [2013-05-06 13:52:00,733] org.apache.zookeeper.server.NIOServerCnxn: Accepted socket connection from /127.0.0.1:55408
INFO  [2013-05-06 13:52:00,741] org.apache.zookeeper.ClientCnxn: Socket connection established to localhost/127.0.0.1:28281, initiating session
INFO  [2013-05-06 13:52:00,772] org.apache.zookeeper.server.NIOServerCnxn: Client attempting to establish new session at /127.0.0.1:55408
INFO  [2013-05-06 13:52:00,774] org.apache.zookeeper.server.persistence.FileTxnLog: Creating new log file: log.1
INFO  [2013-05-06 13:52:00,885] org.apache.zookeeper.ClientCnxn: Session establishment complete on server localhost/127.0.0.1:28281, sessionid = 0x13e7a1cfc8e0000, negotiated timeout = 20000
INFO  [2013-05-06 13:52:00,890] org.apache.zookeeper.server.NIOServerCnxn: Established session 0x13e7a1cfc8e0000 with negotiated timeout 20000 for client /127.0.0.1:55408
Failed to load native Mesos library at /home/rbernal/airbnb-chronos-8ad3f69/lib/org/apache/mesos/mesos/
ERROR [2013-05-06 13:52:01,272] org.apache.zookeeper.server.NIOServerCnxn: Thread Thread[main,5,main] died
! java.lang.UnsatisfiedLinkError: /home/rbernal/airbnb-chronos-8ad3f69/lib/org/apache/mesos/mesos: /home/rbernal/airbnb-chronos-8ad3f69/lib/org/apache/mesos/mesos: cannot read file data: Is a directory

---

When I trying to connect:

INFO  [2013-05-06 13:54:50,335] org.apache.zookeeper.server.NIOServerCnxn: Accepted socket connection from /172.16.1.222:3098
WARN  [2013-05-06 13:54:50,339] org.apache.zookeeper.server.NIOServerCnxn: Exception causing close of session 0x0 due to java.io.IOException: Len error 1195725856
INFO  [2013-05-06 13:54:50,340] org.apache.zookeeper.server.NIOServerCnxn: Closed socket connection for client /172.16.1.222:3098 (no session established for client)

---

Info:

rbernal@ubuntu1204:~$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 12.04 LTS
Release:        12.04

rbernal@ubuntu1204:~$ java -version
java version "1.7.0_17"
Java(TM) SE Runtime Environment (build 1.7.0_17-b02)
Java HotSpot(TM) 64-Bit Server VM (build 23.7-b01, mixed mode)

rbernal@ubuntu1204:~$ mvn -version
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 11:51:28-0200)
Maven home: /opt/apache-maven-3.0.5
Java version: 1.7.0_17, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.7.0/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.2.0-26-virtual", arch: "amd64", family: "unix"

**Comment by ghost** [comment]
Can someone please guide here: https://stackoverflow.com/questions/53783938/org-springframework-context-applicationcontextexception-failed-to-start-bean-o ?
