### ISSUE TITLE
Docker jobs not running when pulling from self-hosted registry

### ISSUE THREAD

**Issue by mindscratch** [mesos/chronos#340]
I am running mesos 0.21.1, marathon 0.7.6 and chronos 2.3.0. I've submitted a docker job using the following JSON

```javascript
{
  "name": "hello",
  "schedule": "R/2015-01-16T11:00:00Z/PT5M",
  "container": {
    "type": "DOCKER",
    "image": "myregistry:5000/myimage"
  },
  "cpus": 0.2,
  "mem": 32.0,
  "command": "echo this is a test"
}
```

The docker image, `myimage` is hosted in a private, self-hosted docker registry. The server for the registry is at `myregistry` on port 5000.

The job shows up in the Chronos UI, and the "schedule" section in the UI updates the time every 5 minutes, however, the # success and error are 0. The mesos UI doesn't show any tasks for this job either. When I tail `/var/log/messages` (this is installed on CentOS6), I don't see any errors.

**Comment by mindscratch** [comment]
FWIW -- I just restarted chronos, and it successfully ran the docker job.

**Comment by rayjohnson** [comment]
I had an issue much like this.  However, mine was that I got a timeout on the task setup from Mesos.  Well if it is a new chronos job it may need to download the Docker image.  This takes longer than the time set for task set-up in Mesos and thus failed.  The second run of the job then worked.

It would be nice if mesos had a different timeout for loading Docker images...

**Comment by clehene** [comment]
@rayjohnson it has see `--executor_registration_timeout` [here](http://mesos.apache.org/documentation/latest/configuration/)

**Comment by elingg** [comment]
hi @mindscratch, yes the property to change would be executor registration timeout. This problem is related to any tasks running docker in marathon or chronos. Did changing that timeout resolve your issue?

**Comment by mindscratch** [comment]
@elingg I've been focusing on Marathon the last couple of months, I believe I'll be looking at using Chronos again soon. If I do, I'll post my observations. Thanks.

**Comment by clehene** [comment]
In the meantime can we close this?
It seems it's a configuration issue with mesos more than anything, perhaps
we could add a note in the documentation about this and raise the mesos
default.

**Comment by mindscratch** [comment]
I think that sounds reasonable. I probably won't get a chance to test this for a few weeks.
