### ISSUE TITLE
Docker Entrypoint and Command always overwritten

### ISSUE THREAD

**Issue by mindscratch** [mesos/chronos#341]
I have tried a variety of docker containers and docker job configurations and have found that the Entrypoint and Command are always overwritten when Chronos runs a docker job.

For example, the Dockerfile I tried had a `ENTRYPOINT ["/bin/start.sh"]`, however, after chronos ran the job, `docker inspect <docker id>` revealed the entrypoint was `/bin/sh`. 

When submitting a Docker job to chronos if the command is left as empty string, Chronos will set that as the command for the docker container, which overwrites whatever the Dockerfile `CMD` was set to.

It appears Marathon does not overwrite the entrypoint. It also supports passing "args" in the event the docker container has a pre-defined `CMD`. I think that approach would be nice for Chronos.

Details:
----------
OS: CentOS 6
Chronos installed with the chronos-2.3.0 rpm.
Command used to start chronos: /usr/local/bin/chronos
Chronos configured via /etc/chronos/conf
     \__ /etc/chronos/conf/http_port  = 8081
     \__ /etc/chronos/conf/master  = zk://myserver:2181/mesos
     \__ /etc/chronos/conf/zk_hosts = zk://myserver:2181/mesos
Mesos version: 0.21.1
java -version: 1.7.0_55

**Comment by mindscratch** [comment]
Looks like if you set `shell` to `false` in the job configuration, things work as expected. This can be closed.

**Comment by wujianqiangwjq** [comment]
I set  shell to false, but  container run failure  from docker-entrypoint .

**Comment by wujianqiangwjq** [comment]
I set  the “shell“” to  false,but I 'm failure which running container from docker-entrypoint.,I sure my image is OK
