### ISSUE TITLE
Chronos support for timezones

### ISSUE THREAD

**Issue by noreenmcm** [mesos/chronos#342]
Does Chronos still only have support for UTC, or does it now  support other timezones? If not, what does the scheduleTimeZone parameter do?

**Comment by elingg** [comment]
Chronos supports timezones. You would have to pass the timezone to the scheduleTimeZone parameter. Please see the example in the readme and let me know if you have further questions. Here is one example where a job is scheduled at 6:32pm in Pacific Standard Time.
{ "schedule": "R/2014-10-10T18:32:00Z/PT60M", "scheduleTimeZone": "PST" }
