### ISSUE TITLE
Chronos re-adds existing jobs when re-elected

### ISSUE THREAD

**Issue by FxChiP** [mesos/chronos#371]
If Chronos is elected leader once, it will load the jobs that need to run and schedule them as normal.

If it then loses and regains leadership, it will not clear the jobs that it was already to schedule, but it will reload them, meaning that some jobs will be scheduled (and run) twice, and possibly more for the number of times that it lost and regained leadership. (Being in a single-leader setup will exacerbate this issue).

**Comment by elingg** [comment]
Thanks for finding this issue! This is duplicated by https://github.com/mesos/chronos/issues/411 so I'm closing this one.
