### ISSUE TITLE
Using a mesos credential interferes with the job scheduler's leader latch...

### ISSUE THREAD

**Issue by swartzrock** [mesos/chronos#401]
In the branch "jason/mesoscredential" I attempted to add support for specifying a mesos credential as a command-line flag. However this causes problems with the job scheduler's leader latch (Curator's LeaderLatch), causing it to return the active leader with an empty id.

**Comment by tamarrow** [comment]
Verified that this works once you specify a credentials flag (with principal + secret) on the mesos master. Thanks @adam-mesos for the help!

**Comment by adam-mesos** [comment]
Note: Also need to use `echo -n "secret" > secret_file` to write the secret to file without trailing newline.

**Comment by elingg** [comment]
Once this is verified, please submit a PR with documentation on how to do the framework authentication with Chronos
