### ISSUE TITLE
scala-maven-plugin:3.1.0 issues

### ISSUE THREAD

**Issue by albdani** [mesos/chronos#41]
I am having issues installing Chronos.
I believe they're related to scala-maven-plugin:3.1.0.
My environment:

-Running CentOS release 6.4 (Final)
- root@eucaclc chronos-master]# /usr/bin/java -version
  java version "1.7.0_19"
  OpenJDK Runtime Environment (rhel-2.3.9.1.el6_4-x86_64)
  OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)
- [root@eucaclc chronos-master]# mvn -version
  Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 08:51:28-0500)
  Maven home: /usr/local/maven
  Java version: 1.7.0_19, vendor: Oracle Corporation
  Java home: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.19.x86_64/jre
  Default locale: en_US, platform encoding: UTF-8
  OS name: "linux", version: "2.6.32-358.6.1.el6.x86_64", arch: "amd64", family: "unix"

Getting the following error:

[INFO] --- scala-maven-plugin:3.1.0:compile (scala-compile-first) @ chronos ---
[INFO] /home/chronos/chronos-master/src/main/java:-1: info: compiling
[INFO] /home/chronos/chronos-master/src/main/scala:-1: info: compiling
[INFO] Compiling 36 source files to /home/chronos/chronos-master/target/classes at 1368735434011
[WARNING] /home/chronos/chronos-master/src/main/scala/com/airbnb/notification/MailClient.scala:53: warning: non variable type-argument String in type pattern Option[String] is unchecked since it is eliminated by erasure
[WARNING]         case (to : String, subject : String, message : Option[String]) => {
[WARNING]                                                        ^
[ERROR] /home/chronos/chronos-master/src/main/scala/com/airbnb/scheduler/config/MainModule.scala:35: error: value setFailoverTimeout is not a member of org.apache.mesos.Protos.FrameworkInfo.Builder
[ERROR] possible cause: maybe a semicolon is missing before `value setFailoverTimeout'?
[ERROR]         .setFailoverTimeout(config.failoverTimeoutSeconds).setUser(config.user).build()
[ERROR]          ^
[ERROR] /home/chronos/chronos-master/src/main/scala/com/airbnb/scheduler/config/ZookeeperModule.scala:14: error: object state is not a member of package org.apache.mesos
[ERROR] import org.apache.mesos.state.ZooKeeperState
[ERROR]                         ^
[ERROR] /home/chronos/chronos-master/src/main/scala/com/airbnb/scheduler/state/MesosStatePersistenceStore.scala:11: error: object state is not a member of package org.apache.mesos
[ERROR] import org.apache.mesos.state.{InMemoryState, State}
[ERROR]                         ^
[ERROR] /home/chronos/chronos-master/src/main/scala/com/airbnb/scheduler/state/Migration.scala:12: error: object state is not a member of package org.apache.mesos
[ERROR] import org.apache.mesos.state.ZooKeeperState
[ERROR]                         ^
[WARNING] one warning found
[ERROR] four errors found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.872s
[INFO] Finished at: Thu May 16 16:17:22 EDT 2013
[INFO] Final Memory: 17M/281M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.0:compile (scala-compile-first) on project chronos: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1(Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by yujinlim** [comment]
Hi,

I have a similar error too

```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building chronos 2.3.0_mesos-0.20.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-antrun-plugin:1.7:run (ant-run-requirejs) @ chronos ---
[INFO] Executing tasks

main:

sourceDir.check:

assets.uptodate:

generateAssets:
     [echo] Combining and minifying JS files.

-optimize:
     [exec] Optimizing (standard.keepLines) CSS file: /root/chronos/src/main/resources/assets/build/scripts/styles/fonts.css
     [exec] Optimizing (standard.keepLines) CSS file: /root/chronos/src/main/resources/assets/build/scripts/styles/lightbox.css
     [exec] Optimizing (standard.keepLines) CSS file: /root/chronos/src/main/resources/assets/build/scripts/styles/pickadate.classic.css
     [exec] Optimizing (standard.keepLines) CSS file: /root/chronos/src/main/resources/assets/build/scripts/styles/pikaday.css
     [exec] Optimizing (standard.keepLines) CSS file: /root/chronos/src/main/resources/assets/build/scripts/styles/vendor/backbone-lightbox/lightbox.css
     [exec]
     [exec] Tracing dependencies for: main
     [exec]
     [exec] Tracing dependencies for: styles
     [exec] Result: 137
     [echo] optimized /root/chronos/src/main/resources/assets/app.build.js with node
[INFO] Executed tasks
[INFO]
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ chronos ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 274 resources to assets
[INFO]
[INFO] --- scala-maven-plugin:3.1.0:add-source (scala-compile-first) @ chronos ---
[INFO] Add Source directory: /root/chronos/src/main/scala
[INFO] Add Test Source directory: /root/chronos/src/test/scala
[INFO]
[INFO] --- scala-maven-plugin:3.1.0:compile (scala-compile-first) @ chronos ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.2
[WARNING]  com.airbnb:chronos:2.3.0_mesos-0.20.1-SNAPSHOT requires scala version: 2.11.2
[WARNING]  mesosphere:chaos_2.11:0.6.1 requires scala version: 2.11.2
[WARNING]  com.fasterxml.jackson.module:jackson-module-scala_2.11:2.4.1 requires scala version: 2.11.1
[WARNING] Multiple versions of scala libraries detected!
[INFO] /root/chronos/src/main/scala:-1: info: compiling
[INFO] Compiling 47 source files to /root/chronos/target/classes at 1421759885465
[WARNING] /root/chronos/src/main/scala/com/airbnb/notification/NotificationClient.scala:25: warning: non-variable type argument String in type pattern Option[String] is unchecked since it is eliminated by erasure
[WARNING]     case (job: BaseJob, to: String, subject: String, message: Option[String]) =>
[WARNING]                                                               ^
[ERROR] OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000007a39ff000, 37310464, 0) failed; error='Cannot allocate memory' (errno=12)
[INFO] #
[INFO] # There is insufficient memory for the Java Runtime Environment to continue.
[INFO] # Native memory allocation (malloc) failed to allocate 37310464 bytes for committing reserved memory.
[ERROR] # An error report file with more information is saved as:
[INFO] # /root/chronos/hs_err_pid31198.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:08.867s
[INFO] Finished at: Tue Jan 20 08:18:28 EST 2015
[INFO] Final Memory: 13M/32M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.0:compile (scala-compile-first) on project chronos: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1(Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Please advice. Thanks
