### ISSUE TITLE
Substandard Release Process

### ISSUE THREAD

**Issue by jeremyjjbrown** [mesos/chronos#415]
We would like to utilize and promote this project but it's Release Management makes that problematic.

**1. Very few releases are tagged**
```bash 
git tag -l
1.0.0
2.0.1
2.1.0
2.3.2
```

**2. Tagged Releases are versioned as SNAPSHOTS and RCs**
```bash
git grep "<version>2.3.2" 2.3.2
2.3.2:pom.xml:  <version>2.3.2_mesos-0.20.1-SNAPSHOT</version>
git grep "<version>2.1.0" 2.1.0
2.1.0:pom.xml:    <version>2.1.0_mesos-0.14.0-rc4</version>
git grep "<version>2.0.1" 2.0.1
2.0.1:pom.xml:    <version>2.0.1_mesos-0.14.0-rc4</version>
```

I'm not sure how you expect users to integrate with your work reliably.

The [Maven Release Plugin](https://maven.apache.org/maven-release/maven-release-plugin/) will automate this for you.

**Comment by ssk2** [comment]
@jeremyjjbrown - thanks for the issue! I agree, we've got plans to improve this procedure, perhaps bringing it in line with what github.com/mesosphere/marathon does.

**Comment by gkleiman** [comment]
@jeremyjjbrown: thanks again for the issue!

As @ssk2  commented, we'll start using the same release process we use for Marathon.

That means that we will:

* Use semantic versioning.
* Start creating release candidates.
* Automate the process as much as possible. We will start with the Maven Release Plugin and probably switch to sbt soon.

**Comment by ssk2** [comment]
Looking forward to this.  Thanks for taking this on Gaston!
