### ISSUE TITLE
Change job config via web UI resets `cpus`, `mem`, etc

### ISSUE THREAD

**Issue by x1a0** [mesos/chronos#426]
Hi,

We add jobs to Chronos by calling REST API in CLI, and we specify `cpus` and `mem` the job needs. However if we later change some settings of that job through web interface - cpu and mem will be set back to some default values.

Is there anyway to keep those settings through web ui?

(_Appended_: It seems web interface is doing the correct request (a PUT) but backend handles POST and PUT in the same way)

Thanks!

**Comment by elingg** [comment]
hello @x1a0, this appears to be a bug with the WEB UI. Thanks for reporting this!  The current workaround is to resubmit the job through the REST API and it will update appropriately.

**Comment by tylerjl** [comment]
+1 to this - not sure what the client-side javascript is doing, but it makes editing jobs almost impossible in the web UI because as soon as I change focus to a second field to edit, the first gets reset within a few seconds. Took me a while to realize I wasn't suffering from short-term memory loss. :sweat_smile:

**Comment by aatkinson-canopy** [comment]
+1   Also, please add an 'advanced' job editor mode that presents all fields. Thanks.

**Comment by philipnrmn** [comment]
@aatkinson-canopy there's already an issue for that #346

**Comment by albundy83** [comment]
runAsUser field is also impacted.
Very annoying... :)

**Comment by elbryan** [comment]
This still happens, it's quite a severe bug

**Comment by albundy83** [comment]
Is it fixed?

**Comment by brndnmtthws** [comment]
This is indeed fixed.
