### ISSUE TITLE
is there some config can expose chronos log to specified folder.

### ISSUE THREAD

**Issue by xiaods** [mesos/chronos#441]
does some option such as log_dir to specified the log dir? i found the log_dir is not working. anyone know it?

**Comment by elingg** [comment]
hi @xiaods, Find the answer you are looking for here: https://github.com/mesos/chronos#debugging-chronos

**Comment by xiaods** [comment]
@elingg the log report the log_dir is invalid parameter. anyone know how to filter the log to specified log file.

**Comment by chengweiv5** [comment]
chronos use a log4j to write log, so a log4j config file we're using to define how chronos logs.

start chronos with below argument

```
-Dlog4j.configuration="file:///path/to/log4j.properties"
```

```
$ cat /path/to/log4j.properties
log4j.rootLogger=info, stdout, R

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout

# Pattern to output the caller's file name and line number.
log4j.appender.stdout.layout.ConversionPattern=%d %5p [%t] (%F:%L) - %m%n

log4j.appender.R=org.apache.log4j.RollingFileAppender
log4j.appender.R.File=/path/to/log4j-log/log

log4j.appender.R.MaxFileSize=10MB
# Keep nine backup file
log4j.appender.R.MaxBackupIndex=100

log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=%d %p %t %c - %m%n
```

Hope to help. Make sure create log directory before start chronos.

**Comment by xiaods** [comment]
@chengweiv5 thanks. it enough.
