### ISSUE TITLE
I am face a challenge to setup local sendmail service.

### ISSUE THREAD

**Issue by xiaods** [mesos/chronos#448]
I want to the chronos master can send email to my email account. I confit the mail_server, and let the job Failure. but i have no any inspect log and clue to tell me the status. anyone have some experience to handle it? thanks a lot.

**Comment by chengweiv5** [comment]
I remember we have some trivial changes to the code to enable email, did you managed to enable chronos log? If so, you'll find some logs I think.

**Comment by xiaods** [comment]
@chengweiv5 my team mate have setup the email successfully. but the setup way can't reproduce again. so i request some way to share. could you please summary the method or a PR?

**Comment by chengweiv5** [comment]
maybe @depay do you a favor.

**Comment by depay** [comment]
@xiaods , could u try thess params?

~~~
 --mail_server xxx.xxx.xxx:xxx
 --mail_user username
 --mail_password xxxxxxxx
 --mail_from username@xxx
 --mail_ssl (if needed)
~~~

**Comment by xiaods** [comment]
@depay thanks for your hints. we have do it, but i found a weird question:
mail_server should be a pop server, do you know what reason?

**Comment by depay** [comment]
@xiaods Mine is a SMTP server:port...did u check the configuration of ur mail service?

**Comment by xiaods** [comment]
@depay i use qq enterprise email. thanks for your share.
