### ISSUE TITLE
Can't start a job immediately. 

### ISSUE THREAD

**Issue by Mongey** [mesos/chronos#452]
According to the docs [here](http://mesos.github.io/chronos/docs/api.html#adding-a-scheduled-job) using an empty string should start a job immediately. 

>The heart of job scheduling is a JSON POST request. The JSON hash you send to Chronos should contain the following fields: 
* Name: the job name 
* Command: the actual command that will be executed by Chronos 
* Schedule: The scheduling for the job, in ISO8601 format, Consists of 3 parts separated by '/': 
  * Number of times to repeat the job; put just 'R' to repeat forever
  * The start time of the job, **an empty start time means start immediately**. Our format is ISO8601:

```bash
curl -L -X POST 
-H 'Content-Type: application/json' 
-d '{"schedule": "R10//PT2S", "name": "SAMPLE_JOB1" ,"command": "pwd"}' 
http://localhost:8081/scheduler/iso8601
```
Chronos response with the following
```
HTTP/1.1 400 Bad Request
Content-Type: application/json
Server: Jetty(8.y.z-SNAPSHOT)
Transfer-Encoding: chunked

Invalid format: ""
```

**Comment by elingg** [comment]
Hi @mongey, I just tried this and it ran successfully, could it be your JSON formatting? I noticed there were some extra spaces in your initial command that I removed. See: ```curl -L -X POST -H 'Content-Type: application/json' -d '{"schedule": "R10//PT2S"
, "name": "elizabethtest" ,"command": "pwd"}' https://chronos.myserver.com/sch
eduler/iso8601```

**Comment by Mongey** [comment]
@elingg 
I think It should be ok... I copy-pasted the above, replacing the ip address.
```bash
curl -L -X POST -H 'Content-Type: application/json' -d '{"schedule": "R10//PT2S" , "name": "elizabethtest" ,"command": "pwd"}' http://192.168.33.10:8081/scheduler/iso8601
```
Still getting the following response.
```
Invalid format: ""
```

For reference I'm using [this repo](https://github.com/everpeace/vagrant-mesos) to setup.

**Comment by elingg** [comment]
Ah! I see the issue, it seems you are running an older version of Chronos. You should try with the latest version 2.3.3 or as a workaround enter the start date instead of using ""

**Comment by Mongey** [comment]
Whoops, didn't realize it wasn't the latest version. I'll boot up a new version and see if that works. Thanks!
