### ISSUE TITLE
Constraints feature documented but not in stable version

### ISSUE THREAD

**Issue by kangman** [mesos/chronos#455]
I found this cool feature documented [here](https://mesos.github.io/chronos/docs/api.html#sample-job)
just below the "Sample Job" section.  It looks like the version in the wild does not have this feature yet.  Can documentation be more clear that this feature is still on available unless built from source?

**Comment by xiaods** [comment]
@kangman read the source code, found the chronos only implement it equal constraint.

**Comment by kangman** [comment]
right, found it.  Thx

On Wed, May 20, 2015 at 5:52 PM, Deshi Xiao <notifications@github.com>
wrote:

> @kangman <https://github.com/kangman> read the source code, found the
> chronos only implement it equal constraint.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesos/chronos/issues/455#issuecomment-104049582>.
>



-- 

All the best,


Daniel S Kang

<http://www.d-kang.com>
<http://www.linkedin.com/pub/daniel-kang/6/58a/53a/>
<https://www.twitter.com/kangman>
