### ISSUE TITLE
how to get one job exec info, including successCount, errorCount and so on.

### ISSUE THREAD

**Issue by hakulat** [mesos/chronos#457]
there is a in Restful API /scheduler/jobs, but this one got all jobs info. 

or could we export some job info to the job env ?

**Comment by elingg** [comment]
For this, you would need to hook Chronos up to Cassandra.

**Comment by wttang** [comment]
could we just add a api and get job info by jobGraph.getJobForName(job) ?

**Comment by xiaods** [comment]
curl -L -X GET http://chronos-node:4400/scheduler/graph/csv
