### ISSUE TITLE
Chronos/docs bug - WEBUI capitalization

### ISSUE THREAD

**Issue by altoplano** [mesos/chronos#469]
The chronos docs contain some information about the webui at:
>   https://mesos.github.io/chronos/docs/webui.html

but the link off the FAQ page under the heading "My Web UI is not showing up!":
>   https://mesos.github.io/chronos/docs/faq.html#web-ui

tries to go to the non-existent:
>   docs/WEBUI.md

Pretty sure if it was just:
>   webui.md

it would work.

**Comment by elingg** [comment]
thanks @altoplano. This is fixed
