### ISSUE TITLE
Chronos doesn't schedule to mesos

### ISSUE THREAD

**Issue by pankaj36** [mesos/chronos#474]
Referring to this discussion : https://groups.google.com/forum/#!searchin/chronos-scheduler/queue/chronos-scheduler/wWfAsKunN04/sbZxy3D7EbQJ

We are facing the same issue where chronos UI is showing jobs in queue, though resources are available. This is because chronos got aborted but UI is still active.

Probable reason could be presence of a task in priority queue even I destroyed that job from UI. I verified this by checking /chronos/state/state/ node, where I can clearly see one job T_ct:1434721179228:1:MyJobID: but this(MyJobID) is not available in chronos UI.

You can reproduce this bug by first starting a job using REST call
curl -L -H 'Content-Type: application/json' -X POST -d '{ "schedule": "R10//PT2S", "name": "MyJobID", "epsilon": "PT15M", "command": "somewrong_command input", "owner": "abc@xyz.com", "async": false, "retries":2 }' chronos-hostname:4040/scheduler/iso8601

Since we are using a wrong command in 'command' field it will fail and chronos will try to relaunch. At this point destroy this job from UI. After some time all new jobs will be enqueued.

A quick fix can be checking a condition jobOption.isEmpty() after line 77 (val jobOption = jobGraph.getJobForName(TaskUtils.getJobNameForTaskId(taskId))) in askManager.scala file, otherwise delete tasks from priority queue after destroying the job.

**Comment by elingg** [comment]
Does this behavior only occur when you destroy a job in the UI? When you use the REST API only are you able to reproduce it? I only ask because I wonder if this is a UI bug.

**Comment by pankaj36** [comment]
Mostly we are using UI for destroying the jobs, but you can reproduce the same using REST delete also, if I remember correc

**Comment by pankaj36** [comment]
Few more observations :
1) I can see chronos under mesos frameworks, though in chronos log it showing "aborting chronos framework"
2) In one instance one good job(sleep 20) is appearing under mesos Running Tasks forever until I cleaned bad tasks from zookeeper node and restarted chronos again.
3) Immediate restart of chronos does not solve this problem, I wonder if this is related to epsilon value of bad job.

**Comment by pankaj36** [comment]
Problem solved.
Issue was related to chronos-2.3.3. After upgrade everything working fine.

**Comment by elingg** [comment]
:+1:
