### ISSUE TITLE
Incorrect documentation around starting Chronos UI

### ISSUE THREAD

**Issue by akshayi1** [mesos/chronos#479]
In the link: http://mesos.github.io/chronos/docs/, there is no way provided to get to the Chronos UI. I had to add `--htto_port 8081` and point to localhost:8081 to access the UI. 

Is this deliberate, or something that was overlooked?

**Comment by elingg** [comment]
This is the expected way. You go to the host and the port where Chronos is deployed. Perhaps the docs should make this clearer (PR's welcome), but it is mentioned in the documentation.
