### ISSUE TITLE
Unable to connect to zookeeper host

### ISSUE THREAD

**Issue by janitachalam** [mesos/chronos#483]
I have five nodes: one mesos master and 4 mesos workers.
On the master, I have zookeeper running. 

But when I attempt to start a chronos instance on my master node with the following commands:

`sudo ./bin/start-chronos.bash --master 10.35.189.53:5050  --zk_hosts 10.35.189.53:2181`
or
`sudo ./bin/start-chronos.bash --master zk://10.35.189.53:2181/mesos --zk_hosts zk://10.35.189.53:2181`

as well as other slight permutations, this error occurs every time:

`21:45:43,912:4700(0x7f12cb5fe700):ZOO_ERROR@handle_socket_error_msg@1721: Socket [10.35.189.53:2181] zk retcode=-4, errno=112(Host is down): failed while receiving a server response`

This is my zoo.cfg file:

`
tickTime=2000
dataDir=/var/zookeeper/
clientPort=2181
initLimit=5
syncLimit=2
`

Any idea as to what the problem could be?

**Comment by kolloch** [comment]
Hi @janitachalam,

try something like 

`--master zk://10.35.189.53:2181/mesos --zk_hosts 10.35.189.53:2181`
