### ISSUE TITLE
Specifying --mesos_role breaks resource allocation.

### ISSUE THREAD

**Issue by jnsaff** [mesos/chronos#487]
We are trying to give different weights to Marathon and Chronos and running into trouble with Chronos. We have two roles specified in mesos: `service,batch`. Marathon is getting service and it works as expected. However when we start chronos with `--mesos_role batch` no Chronos jobs get executed anymore.

When looking at the mesos master `state.json` we see that Marathon has set it's role correctly however Chronos has `role: "*"`.

In Chronos logs we see offers being declined and tasks complaining that there are not enough resources for them: `Found: [cpus: 0.0 mem: 0.0 disk: 0.0]`.

When we remove the `mesos_role` from Chronos everything works again (even while mesos-master is still configured with the `service,batch` roles.

Version: chronos-2.3.4

**Comment by kolloch** [comment]
The chronos logic does not actually respect the roles in the offer.

**Comment by felixb** [comment]
This should be fixed with #462.

**Comment by gkleiman** [comment]
PR #462 has already been merged and it will be part of Chronos v2.4.0-RC1.

Please test either against a snapshot version or the RC once it is released and reopen if the issue still happens.
