### ISSUE TITLE
Chronos crashing frequently

### ISSUE THREAD

**Issue by skaleeswaran** [mesos/chronos#494]
I am running chronos scheduler on port 8081 as a java process. I am seeing that the process stops frequently with the below error. 

F0703 00:54:13.727560  7176 check.hpp:79] Check failed: f.isReady()
*** Check failure stack trace: ***
    @     0x7fb3a1e1cf1d  google::LogMessage::Fail()
    @     0x7fb3a1e1ed5d  google::LogMessage::SendToLog()
    @     0x7fb3a1e1cb0c  google::LogMessage::Flush()
    @     0x7fb3a1e1f659  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb3a1d9bb64  _checkReady<>()
    @     0x7fb3a1d994a4  Java_org_apache_mesos_state_AbstractState__1_1fetch_1get
    @     0x7fb3cd114d08  (unknown)

Mesos version - 0.22.1

**Comment by gkleiman** [comment]
This looks related to the "State abstraction bug" in Mesos.

See https://issues.apache.org/jira/browse/MESOS-1795

You need to use a Mesos version for which this is fixed (both JNI library and master).
