### ISSUE TITLE
Expose chronos job name regex in docs

### ISSUE THREAD

**Issue by srikanth-viswanathan** [mesos/chronos#495]
https://github.com/mesos/chronos/blob/master/src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobUtils.scala#L22 defines the regex that an application name must match.  Please document this explicitly in the user docs.  Note that marathon already does this https://github.com/mesosphere/marathon/blob/master/src/main/resources/mesosphere/marathon/api/v2/AppsResource_create.md#id

**Comment by srikanth-viswanathan** [comment]
Happy to provide doc patch myself. Lemme know.

**Comment by carroux** [comment]
The second link is broken; the corresponding Marathon documentation has been moved here:
https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api/mesosphere/marathon/api/v2/AppsResource_create.md#id-string

**Comment by gkleiman** [comment]
@srikanth-viswanathan: Feel free to create a PR with the doc patch and I'll merge it.

Thanks!

**Comment by carroux** [comment]
@gkleiman: Do you know what the rationale is for using spaces as a delimiter in application names? This causes problems when working with job URLs in scripts and in the command line, for example with xargs. Periods are allowed in Marathon application names and are a sensible delimiter--why aren't they supported in Chronos too?
