### ISSUE TITLE
Chronos monopolizing Mesos Offers 

### ISSUE THREAD

**Issue by joshughes** [mesos/chronos#516]
Our Current deployment.

3 Master Nodes running 
 * Mesos Master - `0.22.1-1.0.ubuntu1404`
 * Marathon - `0.8.1-1.0.171.ubuntu1404`
 * Chronos - `2.3.3-1.0.1.ubuntu1404`

3 Slave Nodes running: 
   * Mesos Slave - `0.22.1-1.0.ubuntu1404`

The symptoms we are seeing is that chronos monopolizes all the offers causing Marathon to no longer be able to deploy anything to Mesos. In the latest extreme case is seems as if Chronos itself could no longer run tasks because it had consumed all the offers from Mesos. 

To be clear our Mesos cluster has plenty of resources, it just seems that Chronos is not releasing the offers. My team has commented on this in the issue https://github.com/mesos/chronos/issues/381

We thought we had worked around the issue by creating what we call a "Release Resources" task in Chronos. This task is just `sleep 5s` and is scheduled to run every 5 seconds. The problem generally occurs after Chronos has been sitting idle and no tasks have been run through the system for a period of time. At first that period of time seemed to be weeks, but now we are seeing it occur more often. 

It is worth noting that our usage pattern for the Chronos has changed. This could explain why the duration of time between incidents has also changed. Where there were not many jobs running before, we now have more consistent flow of tasks into the Chronos service. There still are hours where the Chronos server may not be running tasks though, since most of our tasks are not reoccurring at this point in time. 

@apriendeau @bcarpio @jkrukoff  @ssk2

**Comment by kolloch** [comment]
This might or might not be related to https://github.com/mesos/chronos/issues/509. Since you are only running very few frameworks this is probably another issue, though.

It would be helpful if you provided your master state.json (http://master.mesos:5050/state.json).

Do you see a lot of "Offered Resources" in the overview of the Mesos UI (left side bar)?

**Comment by joshughes** [comment]
@kolloch currently we aren't experiencing the issue. When the issue is present I can confirm that I see many 'Offered Resources' in the Mesos UI. During the next event our team will ensure we screen shot the Offered Resources UI. I did see that UI full of Resources offered to Chronos if that is what your thinking.

**Comment by gkleiman** [comment]
This should have been fixed by #510. Please reopen if you this happens to you again.
