### ISSUE TITLE
Schedule a new release

### ISSUE THREAD

**Issue by andygrunwald** [mesos/chronos#529]
Hey,

since the last release (v2.3.4 / May 19) a lot (~60) commits were made to master.
And even some really interesting changes (from my point of view) are in it:

* A lot of documentation changes
* Issue 473: Generic Http callback for failed jobs in Chronos > https://github.com/mesos/chronos/commit/2f565bd2ddb7bf6272b174c96fe8f8751e0b9ad7
* Docker improvements

I would love to see #518 as released as fast as possible to use it in production.

A list of complete commits: https://github.com/mesos/chronos/compare/2.3.4...master

Is there the next release (v2.3.5 / v2.4.0) scheduled in the (very near) future?
Is there a "timeframe" of releases?

Of course an alternative is to your production system on master, but i try to avoid this if a release is possible.

> Ship early, ship often ;)

**Comment by gkleiman** [comment]
Good timing, we plan to release v2.4.0-RC1 this week. If it proves to be stable, then we'll release v2.4.0 next week.

You can see a more detailed change log in changelog.md.

**Comment by gkleiman** [comment]
Closing this, as v2.4.0-RC1 was release yesterday.
