### ISSUE TITLE
Cassandra as statistic backend: Why? And are other databases welcome?

### ISSUE THREAD

**Issue by andygrunwald** [mesos/chronos#564]
Hey,

this is not directly an issue. More like a small question / discussion.
As we know Chronos has Cassandra support as statistic backend.

I was wondering why Cassandra was chosen.
Is there a special reason for it? Or was there a discussion or something similar?
Don`t get me wrong. Cassandra is a good database. I only want to know the background.

This leads me to another question:
Are other databases like MySQL or PostgreSQL welcome as well as statistic backend?
As far as i can see all operations Chronos do with Cassandra are able to do with those databases as well.
Maybe if we adjust the source code a little bit databases like Redis are also possible (of course we need to adjust query / storage / key generation).
But the main question is: Are they welcome (maybe as contribution)?
Or is there not so much chance to get such features in?

Or (maybe) a better idea: A HTTP statistic callback (similar to the HTTP failure callback).
If a job would start writing statistics a HTTP callback will be fired (against a URL).
What is behind this URL is the area of the company / developer. But this would create a mass at flexibility.

Do you see such feature as useful? Or a waste of time?
And is there some background why Cassandra?

I like to get some feedback. Thank you :)

**Comment by SEJeff** [comment]
If the callback was just a [webhook](http://www.webhooks.org/), this could be somewhat generic.

**Comment by andygrunwald** [comment]
My colleague @bidesh created PR for this feature. Checkout https://github.com/mesos/chronos/pull/593
Maybe you (@SEJeff and @orlandohohmeier) can have a look at it and provide a little bit of feedback?

My initial question is more or less solved with the PR.
