### ISSUE TITLE
how child job get its parents job result? in other words, how job results as parameters pass from parent job to child job?

### ISSUE THREAD

**Issue by junneyang** [mesos/chronos#574]

**Comment by orlandohohmeier** [comment]
I'm afraid you can't pass results from a parent job to a child job. You’d typically use some sort of stateful service to store such things like hdfs, cassandra, etc.

**Comment by orlandohohmeier** [comment]
I've opened a feature request (#577) to add a chronos functionality to pass result from parent to child jobs. Feel free to add some details.
