### ISSUE TITLE
How to select exact slave for job?

### ISSUE THREAD

**Issue by altvnk** [mesos/chronos#576]
Tried constraint used in marathon with no success:
` "constraints": [["hostname", "LIKE", "slave-03"]]`

**Comment by orlandohohmeier** [comment]
It's not possible to use "hostnames" in constraints yet, but it will once #563 is merged. In the meantime you may be able to get the right node using different attributes. For a documentation on how to use constraint please see: https://mesos.github.io/chronos/docs/api.html#constraints
