### ISSUE TITLE
Edits in chronos ui break docker jobs

### ISSUE THREAD

**Issue by rvm2015** [mesos/chronos#582]
It appears if you create a job using the /scheduler api that uses docker, and then turn around and edit that job in the web ui (by say changing the run time) it doesn't retain the docker components.

Easily testable, I'm seeing subsequent runs of the job fail with an error saying they're unable to find the command from the job. If I delete and recreate the job with the api it works normally.

**Comment by Sodki** [comment]
Would this be a duplicate of #426?

**Comment by rvm2015** [comment]
Yes, I'll close as duplicate.
