### ISSUE TITLE
Travis CI not building since 20th of October

### ISSUE THREAD

**Issue by hermansc** [mesos/chronos#585]
https://travis-ci.org/mesos/chronos/builds

I.e. not giving feedback on pull requests etc. either.

**Comment by ssk2** [comment]
Thanks for the heads up @hermansc! 

@brndnmtthws - do you have access to the project settings? Can you check the configuration? It looks like everything is fine in Travis CI, so I'm wondering what happened here.

**Comment by brndnmtthws** [comment]
I reset everything. Seems to be working now.

**Comment by ssk2** [comment]
Thank you @brndnmtthws!
