### ISSUE TITLE
Many or long arguments cause too large a task identifier

### ISSUE THREAD

**Issue by mcoffin** [mesos/chronos#604]
# Overview

When you have many arguments, and those arguments or of any significant length, the task ID created by Chronos is too long and the task will remain forever in the queued state as it's state will become `TASK_ERROR`.

Critically, for reasons unknown to me, after this happens, **all** tasks in Chronos will no longer run at all as scheduled even after restarting Chronos. The only respite I've found here is to actually delete the tasks and re-create them!

Is there even a good reason that arguments are concatenated in to the task ID?

# Workaround

For those here looking for a solution, I just let bash do the parsing of my arguments for me, putting all my args (and the desired command) in to the `command` field of the Chronos task, and setting `shell` to `true` so that Chronos will override the docker entrypoint with `/bin/bash`. It's obviously not the ideal solution, but it will work for the time being.

# Steps to reproduce

1. Create a Chronos task with a single small command and a fair amount (6-ish) of arguments that are all at least a little bit long (10chars maybe?).
2. You may have to include getopt-style arguments as well to reproduce as I haven't tried it without them yet (i.e. `-m`).
3. The second argument in my arguments was a URL, you may have to include a URL to reproduce (maybe because of the colon?).
4. If it's still not reproducable there, the FIRST argument of mine was a getopt style arg.

```json
{
    "arguments": [
        "-m", "http://someHost:8080/path",
        "-r", "someStuff",
        "-g", "moreStuff",
        "-g", "evenMoreStuff",
        "-g", "stillYetMoreStuff"
    ]
}
```

**Comment by asottile** [comment]
I think this is actually a dupe of #568

**Comment by mcoffin** [comment]
That it is.
