### ISSUE TITLE
Support Mesos fetcher cache

### ISSUE THREAD

**Issue by turb** [mesos/chronos#611]
It would be awesome if Chronos supported Mesos fetcher cache introduced in 0.23, see http://mesos.apache.org/documentation/latest/fetcher/

As far as I see:
* the easy part is to set the `cache` attribute at MesosTaskBuilder.scala:87
* the delicate part is the introduction of this new parameter in Chronos API (and other attributes, by the way)

Marathon is also speaking about it here: mesosphere/marathon#1953

Thanks!

**Comment by turb** [comment]
FYI this feature has been released in Marathon 0.15, see https://github.com/mesosphere/marathon/releases/tag/v0.15.0

I can work on a PR to have the same API-breaking modification, but I would prefer to have some feedback on its opportunity before doing it.

**Comment by djzort** [comment]
+1 super usefull
