### ISSUE TITLE
Chronos WebUi support for configuring docker jobs

### ISSUE THREAD

**Issue by vivekkothari** [mesos/chronos#641]
Hi,

I created a Docker job through the REST API.
It's now visible on UI. Now let's say I want to edit the owner / schedule, I edit it and save it.
Now my docker container settings are lost, I again have to use the REST API to edit the job which is extremely frustrating.

UI doesn't support entering Docker container parameters (Marathon UI now supports it). The UI needs a major update. I can't see the job History too.

**Comment by ddossot** [comment]
Job history shows only if you have Cassandra configured, is that the case for you?

**Comment by vivekkothari** [comment]
No..I am not using Cassandra as of now. I can live with the job history not showing on UI for now, but not being able to edit Jobs from UI is a major letdown.

**Comment by xiaods** [comment]
it's not reasonable. just use command to apply your parameters .

**Comment by erSitzt** [comment]
Why should this not be reasonable ?
If there is an UI it should be possible to modify all settings of a job or at least not destroy the config.
Marathon does this beautifully by providion the JSON view for a task, where all options that are not available in the UI can be used and seen...

**Comment by vivekkothari** [comment]
@erSitzt 👍

**Comment by tomwganem** [comment]
@erSitzt 👍

**Comment by gengmao** [comment]
In Chronos 3.0 we can edit container info now.
