### ISSUE TITLE
Does Chronos run with Mesos v0.27 and v0.28?

### ISSUE THREAD

**Issue by andygrunwald** [mesos/chronos#655]
The [Mesos Upgrade guide](http://mesos.apache.org/documentation/latest/upgrades/) describes several changes to their API:

v0.27:
* Allocator API
* More calls to the `executorLost` callback
* The isolator prepare interface has been changed

Is Chronos affected by these changes? Or is anyone running Chronos on Mesos v0.27 or v0.28 in production?

**Comment by turb** [comment]
FYI, we do run Chronos on Mesos 0.27.2 without any problem.

**Comment by aatkinson-canopy** [comment]
0.28.0 without issue here.

**Comment by Spritekin** [comment]
I have been running with 0.27 and then 0.28 for months. No problem.

**Comment by andygrunwald** [comment]
Thanks for all the responses. We upgraded today and it works fine

**Comment by BrickXu** [comment]
Very useful ticket for running chronos with mesos 0.28, Thanks all.
