### ISSUE TITLE
Support for username / password credentials for Cassandra

### ISSUE THREAD

**Issue by andygrunwald** [mesos/chronos#658]
Chronos supports Cassandra as a statistic / metrics backend.
If you are running Cassandra with an auth required you are not able to use Cassandra with Chronos, because it don`t support username / password configurations.

The configuration settings are missing in https://github.com/mesos/chronos/blob/88522b574c491489662509fae09153c43bb61397/src/main/scala/org/apache/mesos/chronos/scheduler/config/CassandraConfiguration.scala
The connection is not build with username / password in https://github.com/mesos/chronos/blob/88522b574c491489662509fae09153c43bb61397/src/main/scala/org/apache/mesos/chronos/scheduler/config/JobStatsModule.scala

In the builder the [withCredentials](http://docs.datastax.com/en/drivers/java/2.0/com/datastax/driver/core/Cluster.Builder.html#withCredentials-java.lang.String-java.lang.String-) method is handy here.

**Comment by xiaods** [comment]
@andygrunwald,  how about apply a PR
