### ISSUE TITLE
Docker entry point and arguments are not working

### ISSUE THREAD

**Issue by mtkshakeel** [mesos/chronos#666]
Hi All,

I am running a docker image with an entrypoint that takes two args. One of the args (args1) is a script and the other one is an args to the script like (--args2).

The docker entrypoint works properly with the two args on the command line. 
i.e docker run image "args1" "--args2"

However when I try to load the docker image using chronos + docker json file it does not work.

There does not seem to be an option for to pass only arguments to a docker image. The arguments options seems to be limited to normal commands.

I've tried passing the entrypoint on the command line with shell=false and the args with the arguments option, the job stays in the queued state permanently

If I try to pass the entrypoint with the two args using the command option, it fails 
i.e "command": "entrypoint-exe args1 --args2"

even "command": "entrypoint-exe \"args1\" \"--args2\""
fails

**Comment by mtkshakeel** [comment]
I've managed to bypass the problem by passing my arguments as environment variables to the docker image.

**Comment by dizney** [comment]
For reference: I noticed it does work when you set shell to false, put the first argument in command and the rest of the arguments in arguments.
Eg for the bobrik/curator container which has an entrypoint but no cmd (https://hub.docker.com/r/bobrik/curator/~/dockerfile/) i use:

`"shell": false,
"command": "--config",
"arguments": [
  "/etc/curator/config.yml",
  "/etc/curator/actions.yml"
]`
