### ISSUE TITLE
Spark_python job not Working on Dcos chronos Env

### ISSUE THREAD

**Issue by slankipalli** [mesos/chronos#680]
Spark python job not working on chronos, Chronos running on Dcos environment. I build Docker image with spark and python dependencies 

I0510 14:43:19.216224  6301 exec.cpp:143] Version: 0.28.1
I0510 14:43:19.220377  6315 exec.cpp:217] Executor registered on slave 671bdf57-caeb-44c9-b382-a84043e7cc23-S5
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/05/10 14:43:23 INFO SparkContext: Running Spark version 1.4.1
16/05/10 14:43:23 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/05/10 14:43:23 INFO SecurityManager: Changing view acls to: root
16/05/10 14:43:23 INFO SecurityManager: Changing modify acls to: root
16/05/10 14:43:23 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); users with modify permissions: Set(root)
16/05/10 14:43:24 INFO Slf4jLogger: Slf4jLogger started
16/05/10 14:43:24 INFO Remoting: Starting remoting
16/05/10 14:43:24 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriver@172.16.2.216:60004]
16/05/10 14:43:24 INFO Utils: Successfully started service 'sparkDriver' on port 60004.
16/05/10 14:43:24 INFO SparkEnv: Registering MapOutputTracker
16/05/10 14:43:24 INFO SparkEnv: Registering BlockManagerMaster
16/05/10 14:43:24 INFO DiskBlockManager: Created local directory at /tmp/spark-298324d8-a187-4ccd-a65f-ebae5d7cd362/blockmgr-10f614a8-d0e7-4804-ae4d-eeb0da2153c2
16/05/10 14:43:24 INFO MemoryStore: MemoryStore started with capacity 265.4 MB
16/05/10 14:43:24 INFO HttpFileServer: HTTP File server directory is /tmp/spark-298324d8-a187-4ccd-a65f-ebae5d7cd362/httpd-ce5ffb91-418c-463e-b676-02ace110d297
16/05/10 14:43:24 INFO HttpServer: Starting HTTP Server
16/05/10 14:43:24 INFO Utils: Successfully started service 'HTTP file server' on port 36004.
16/05/10 14:43:24 INFO SparkEnv: Registering OutputCommitCoordinator
16/05/10 14:43:25 INFO Utils: Successfully started service 'SparkUI' on port 4040.
16/05/10 14:43:25 INFO SparkUI: Started SparkUI at http://172.16.2.216:4040
16/05/10 14:43:25 INFO Utils: Copying /opt/spark/dist/cleantrips/bin/spark_test.py to /tmp/spark-298324d8-a187-4ccd-a65f-ebae5d7cd362/userFiles-c3b4b65f-065b-4c81-a087-0930e3606d32/process_with_spark.py
16/05/10 14:43:25 INFO SparkContext: Added file file:/opt/spark/dist/clean/bin/spark_test.py at http://172.16.2.216:36004/files/spark_test.py with timestamp 1462891405289
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0510 14:43:25.419803   127 process.cpp:868] Failed to initialize: Failed to bind on 10.0.1.202:0: Cannot assign requested address: Cannot assign requested address [99]
*** Check failure stack trace: ***
Aborted (core dumped)

spark-dcoker.json file

{
 "schedule": "R/2016-05-10T14:41:00Z/PT24H",
 "name": "sparkdockerjob1",
 "container": {
   "type": "DOCKER",
   "image": "dockers/tests:1.1",
   "network": "BRIDGE",
   "volumes": [
     {
       "containerPath": "/var/log/",
       "hostPath": "/logs/",
       "mode": "RW"
     }
   ]
 },
 "cpus": "0.5",
 "mem": "512",
 "uris": [],
  "command": "/opt/spark/dist/bin/spark-submit  --master mesos://leader.mesos:5050/mesos --executor-memory 2g --conf spark.mesos.coarse=true --conf spark.mesos.executor.docker.image=dockers/tests:1.1 /opt/spark/dist/clean/bin/spark_test.py testbucket Dcos-d-in Dcos-d-op "
}

**Comment by jgarcia-mesosphere** [comment]
Hello!

Looking at this line 
```
F0510 14:43:25.419803 127 process.cpp:868] Failed to initialize: Failed to bind on 10.0.1.202:0: Cannot assign requested address: Cannot assign requested address [99]
```

it looks like Spark's attempt to open a network port failed. Do you get better results trying a similar job in Marathon?

**Comment by slankipalli** [comment]
Same job it works fine in Marathon,but I want to run in chronos because it is scheduled job

**Comment by jgarcia-mesosphere** [comment]
Are you using automatic port assignment in Marathon? If so, that may not work the same in Chronos because it looks like Spark is trying to bind port `0` which may not be possible.

**Comment by air** [comment]
Confirmed that Chronos doesn't support ports, see #460

**Comment by slankipalli** [comment]
What is Solution for this problem then @air  and @jgarcia-mesosphere

**Comment by jgarcia-mesosphere** [comment]
Looking at it from this high-level view, the solution to the mis-configuration in your app definition is to specify a port for the service. Unfortunately, this is a poor place to get into the details I'd need to confirm. Mind meeting us in dcos-community.slack.com or sending a support issue to support@mesosphere.com so we can dig in further?

**Comment by jgarcia-mesosphere** [comment]
It looks like we're trying to use `0` for the `LIBPROCESS_PORT, by defining it as an environment variable at the agent level.

**Comment by MarcinMilewski** [comment]
You need to change Bridged network type to Host.
