### ISSUE TITLE
Retain most recent job statusCode returned, and expose in hash returned by e.g. /status/jobs

### ISSUE THREAD

**Issue by avi8tr** [mesos/chronos#682]
When an async job writes its statusCode to Chronos' /scheduler/task/<task id> endpoint prior to exiting, Chronos interprets any nonzero statusCode as failure.  Currently, however, the statusCode itself is logged (if INFO logging is enabled) and discarded, depriving the REST client of failure-related information relayed by the job in the statusCode.  Alternative mechanisms such as mis-using the job progress reporting mechanism are (much) more complicated and susceptible to races. Please retain the statusCode for the most recent execution and expose it in hashes of the job status query endpoints.

**Comment by brndnmtthws** [comment]
The concept of async jobs has been deprecated.
