### ISSUE TITLE
Chronos 2.5.0 release

### ISSUE THREAD

**Issue by vineethvarghese** [mesos/chronos#684]
Guys,

When would it be possible to release 2.5.0 version of Chronos? There are a lot of fixes in there that would make life a whole lot easier ;).

**Comment by andy-miracl** [comment]
Id like to second that request. We think chronos is great but we really need the custom docker parameters feature.

**Comment by lhoss** [comment]
the last release is exactly 1 year old, in 3 days :(
we are fighting with many issues, some of which seems solved in master !

**Comment by tsaridas** [comment]
+1

**Comment by fpgeek** [comment]
+1

**Comment by lhoss** [comment]
https://dcos.io/releases/1.8.0/
> There is now built-in support of running scheduled jobs. We created a new Apache Mesos framework called Metronome. Metronome is integrated natively with DC/OS and is available from the Jobs tab on the DC/OS UI.
> ...
> Metronome will likely replace Chronos as our DC/OS job framework. If you still need Chronos, you can get it from the DC/OS Universe.

Still they should get out a newer release of chronos (with all the fixed done)

**Comment by tchoedak** [comment]
+1 There's a lot of great fixes that would be great to have in a new release

**Comment by kevtaylor** [comment]
@brndnmtthws Brenden - would you be able to post a statement to us, regarding the status and future of this project and when we might get a release of all the features/fixes?

**Comment by brndnmtthws** [comment]
I intend to cut a release in the near future.

**Comment by dangra** [comment]
why do you close the ticket if you _intend to release_ but it is not released yet?

**Comment by brndnmtthws** [comment]
If you'd like to speed things up, please take the `:latest` image for a test drive and report issues. Quite a bit has changed, so it may require some finagling.

There's a PR for the DC/OS package here: https://github.com/mesosphere/universe/pull/851

**Comment by brndnmtthws** [comment]
I've also written some instructions here for testing: https://gist.github.com/brndnmtthws/c482b9db287fd3928bd436dadbd0ed34

**Comment by jodem** [comment]
thanks @brndnmtthws, what would be the way to have the 3.0 version for those that do not use DC/OS ?

**Comment by brndnmtthws** [comment]
@jodem 

Quick and easy:

```
$ docker run --net=host -e PORT0=8080 -e PORT1=8081 mesosphere/chronos:latest --zk_hosts 192.168.65.90:2181 --master zk://192.168.65.90:2181/mesos
```

Where `192.168.65.90` is the master/ZK IP.

**Comment by jodem** [comment]
OK thx I'll deploy as any marathon app then (currently we don't use chronos packaged as a docker container but from mesos OS packages).
