### ISSUE TITLE
A task with the same taskid is scheduled twice, back-to-back

### ISSUE THREAD

**Issue by huadongliu** [mesos/chronos#722]
We have a job that is scheduled every two minutes PT2M. Below log shows the job was run three times. The first two are expected while the third one is not.

1st
`[2016-09-17 23:57:53,147] INFO Size of streams: 11 (org.apache.mesos.chronos.scheduler.jobs.JobScheduler:490)`
`[2016-09-17 23:57:53,147] INFO Checking schedules with time horizon:PT60S (org.apache.mesos.chronos.scheduler.jobs.JobScheduler:482)`
`[2016-09-17 23:57:53,147] INFO Calling next for stream: R/2016-09-18T06:58:00.000Z/PT2M, jobname: JOB NAME (org.apache.mesos.chronos.scheduler.jobs.JobScheduler:512)`
`[2016-09-17 23:57:53,147] INFO Task ready for scheduling: 2016-09-18T06:58:00.000Z (org.apache.mesos.chronos.scheduler.jobs.JobScheduler:545)`
`[2016-09-17 23:57:53,147] INFO Scheduling: JOB NAME (org.apache.mesos.chronos.scheduler.jobs.JobScheduler:667)`
`[2016-09-17 23:57:53,147] INFO Scheduling task 'ct:1474181880000:0:JOB NAME:' with delay: '6853' (org.apache.mesos.chronos.scheduler.jobs.TaskManager:192)`
`[2016-09-17 23:57:53,148] INFO State T_ct:1474181880000:0:JOB NAME: does not exist yet. Adding to state (org.apache.mesos.chronos.scheduler.state.MesosStatePersistenceStore:77)`

2nd
`[2016-09-17 23:59:53,208] INFO Size of streams: 11 (org.apache.mesos.chronos.scheduler.jobs.JobScheduler:490)`
`[2016-09-17 23:59:53,208] INFO Checking schedules with time horizon:PT60S (org.apache.mesos.chronos.scheduler.jobs.JobScheduler:482)`
`[2016-09-17 23:59:53,209] INFO Calling next for stream: R/2016-09-18T07:00:00.000Z/PT2M, jobname: JOB NAME (org.apache.mesos.chronos.scheduler.jobs.JobScheduler:512)`
`[2016-09-17 23:59:53,209] INFO Task ready for scheduling: 2016-09-18T07:00:00.000Z (org.apache.mesos.chronos.scheduler.jobs.JobScheduler:545)`
`[2016-09-17 23:59:53,209] INFO Scheduling: JOB NAME (org.apache.mesos.chronos.scheduler.jobs.JobScheduler:667)`
`[2016-09-17 23:59:53,209] INFO Scheduling task 'ct:1474182000000:0:JOB NAME:' with delay: '6791' (org.apache.mesos.chronos.scheduler.jobs.TaskManager:192)`
`[2016-09-17 23:59:53,210] INFO State T_ct:1474182000000:0:JOB NAME: does not exist yet. Adding to state (org.apache.mesos.chronos.scheduler.state.MesosStatePersistenceStore:77)`

3rd
`[2016-09-18 00:00:04,014] INFO Checking schedules with time horizon:PT60S (org.apache.mesos.chronos.scheduler.jobs.JobScheduler:482)`
`[2016-09-18 00:00:04,014] INFO Task ready for scheduling: 2016-09-18T07:00:00.000Z (org.apache.mesos.chronos.scheduler.jobs.JobScheduler:545)`
`[2016-09-18 00:00:04,015] INFO Scheduling: JOB NAME (org.apache.mesos.chronos.scheduler.jobs.JobScheduler:667)`
`[2016-09-18 00:00:04,015] INFO Scheduling task 'ct:1474182000000:0:JOB NAME:' with delay: '0' (org.apache.mesos.chronos.scheduler.jobs.TaskManager:192)`
`[2016-09-18 00:00:04,018] INFO Key for state exists already: T_ct:1474182000000:0:JOB NAME: (org.apache.mesos.chronos.scheduler.state.MesosStatePersistenceStore:79)`
`[2016-09-18 00:00:04,026] INFO State update successful: true (org.apache.mesos.chronos.scheduler.state.MesosStatePersistenceStore:92)`
`[2016-09-18 00:00:04,027] INFO Triggering: 'JOB NAME' (org.apache.mesos.chronos.scheduler.jobs.TaskManager:20)`
`[2016-09-18 00:00:04,027] INFO Removing task mapping (org.apache.mesos.chronos.scheduler.jobs.TaskManager:123)`

The first two runs completed successfully.

`[2016-09-18 00:00:05,950] INFO Task with id 'ct:1474182000000:0:JOB NAME:' FINISHED (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:221)`
`[2016-09-18 00:00:05,951] INFO Purging entry 'T_ct:1474182000000:0:JOB NAME:' via: org.apache.mesos.state.ZooKeeperState (org.apache.mesos.chronos.scheduler.state.MesosStatePersistenceStore:168)`

The 3rd failed with REASON_EXECUTOR_TERMINATED because it ran back to back with the 2nd one, with the same task ID. Mesos was trying to reuse the same executor from the 2nd run (because of the same task ID) and then the executor terminated. 

`[2016-09-18 00:00:06,951] INFO Task with id 'ct:1474182000000:0:JOB NAME:' FAILED (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:229)`
`[2016-09-18 00:00:06,951] WARN Task of job: JOB NAME failed. (org.apache.mesos.chronos.scheduler.jobs.JobScheduler:378)`

**Comment by dandew** [comment]
I have noticed a similar stampede when retries happen at the same time that the job regularly fires: some retries are skipped altogether in some cases. Maybe related?

**Comment by brndnmtthws** [comment]
This should _hopefully_ be resolved in the next release.

**Comment by huadongliu** [comment]
@brndnmtthws, could you please point me to the commit that fixed the bug? Thank you.

**Comment by brndnmtthws** [comment]
https://github.com/mesos/chronos/commit/23667531fec3f920d6a35352ade4f628a9f453db
