### ISSUE TITLE
Malformed Header on 401 responses

### ISSUE THREAD

**Issue by hylandm** [mesos/chronos#735]
When attempting to authenticate with a token a bad 401 response header is returned. 

`e.g. curl -k -X GET -i -H "Authorization: token=WRONG" <chronos_server>/chronos/scheduler`
returns a header: `WWW-Authenticate: oauthjwt`

This causes errors in many http libraries such as pythons httplib2.
A proper header might be: `WWW-Authenticate: Bearer error="invalid_token" error_description="Requires authentication"`

**Comment by brndnmtthws** [comment]
Are you trying to access the Chronos API through adminrouter? Chronos doesn't set this header.

**Comment by hylandm** [comment]
You're right
