### ISSUE TITLE
Latest docker image mesosphere/chronos is broken

### ISSUE THREAD

**Issue by jqcorreia** [mesos/chronos#745]
As my unit file was force pulling the latest image I ended up with a broken Chronos image. 
The command name itself is more than not needed, it just refuses to launch. (Easily fixable from my side)

The default Web entrypoint is broken too since it can't reach 'bundle.js' as stated by devtools.
I'm back to using v3.0.0-pre0-3-gb4ed531 (which I version-fixed this time)
Just an heads up. Other than that, excellent work

**Comment by nurcahyo** [comment]
I think you should write the issue here

**Comment by brndnmtthws** [comment]
Please don't use `:latest`, unless you're okay with debugging these sort of issues.

Anyway, it should be updated now. I'm working to get a release out as soon as I can do enough testing (and find most of the new bugs).
