### ISSUE TITLE
build error chronos - maven errors

### ISSUE THREAD

**Issue by 3dlex** [mesos/chronos#75]
Hello airbnb and others,

I have been looking at chronos and have been pretty excited about getting it running.

I have tried installing Chronos multiple times following directions and have not had success.

So I decided to rebuild everything from scratch, including zookeeper and mesos.

I downloaded zokeeper-3.4.4. (If I use included zookeeper I cannot get mesos to connect.)
Extracted to /opt/zoo
I setup conf file:
tickTime=2000
initLimit=10
syncLimit=5
dataDir=/opt/zoo/data
dataLogDir=/opt/zoo/log
clientPort=2181

I create /opt/zoo/data and log

I run bin/zkServer.sh start and all is working.
netstat -an | grep 2181
tcp        0      0 0.0.0.0:2181                0.0.0.0:\*                   LISTEN  
tcp        0      0 127.0.0.1:2181              127.0.0.1:54670             ESTABLISHED

I extract mesos-0.12.0-incubating.tar.gz to /opt/mesos
cd /opt/mesos
./bootstrap 
./configure --with-webui --disable-perftools (If I use included zookeeper I cannot get mesos to connect.)
make
make install

(I also perform the same on a second server.)

On first server I execute:
/usr/local/sbin/mesos-master --zk=zk://localhost:2181/mesos
/usr/local/sbin/mesos-slave --master=zk://localhost:2181/mesos

I http to server and success!! I see master and 1 slave.

I hop on to the second box and execute:
/usr/local/sbin/mesos-slave --master=zk://192.168.1.100:5050

This also connects as slave! (I'm not sure if this is the proper way to setup 2nd server, but we will come back as this is the farthest I have gotten.)

Now to Chronos
Download zip file and extract to /opt/chronos-master
cd chronos-master
maven package
Results :

Tests in error: 
  PersistenceStoreSpec » Throwable UnsupportedClassVersionError: org/apache/meso...
  JobUtilsSpec » Throwable UnsupportedClassVersionError: org/apache/mesos/state/...

Tests run: 36, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:33.751s
[INFO] Finished at: Mon Jul 22 18:39:24 EDT 2013
[INFO] Final Memory: 38M/524M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.14.1:test (default-test) on project chronos: There are test failures.
[ERROR] 
[ERROR] Please refer to /opt/chronos-master/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

so I run:
mvn clean install -U
same results.

If I try using installer script it ends in build failures.

Both systems:
uname -a
Linux CHN01 2.6.32-358.14.1.el6.x86_64 #1 SMP Mon Jun 17 15:54:20 EDT 2013 x86_64 x86_64 x86_64 GNU/Linux
2 CPU
4 GB RAM
20 GB HDD (Only chronos running here.)

Thoughts?
Thanks!

**Comment by wangqunOne** [comment]
@3dlex I also meet the issue. Can you send me the doc how to install chronos successfully? My emails is bjwqun@cn.ibm.com

Thanks.
