### ISSUE TITLE
Async task support?

### ISSUE THREAD

**Issue by dave-handy** [mesos/chronos#760]
It seems like asynchronous task support was removed in 3.0.0, but it is still mentioned in the docs. I don't see any references in the source to support this feature, except for an unreferenced case class in one of the REST API endpoints. (Search for `statusCode` to find it.)

To be more specific, if I add the `"async": true` flag to a job, it is simply removed from the job definition when I save.

I never had much luck with async tasks in 2.x, but if this feature is completely gone, it should be noted in the release notes and removed from the documentation. Just had a very frustrating experience with the parameter magically disappearing.

**Comment by brndnmtthws** [comment]
Yep, good point. I forgot to mention it in the release notes. I'll update accordingly.
