### ISSUE TITLE
epsilon and retries difference

### ISSUE THREAD

**Issue by batizty** [mesos/chronos#767]
Hi,

I am using chronos in CentOS 7 and the version is chronos-2.4.0-0.1.20151007110204.el7.x86_64.

Epsilon i picked from Doc site "epsilon: If Chronos misses the scheduled run time for any reason, it will still run the job if the time is within this interval. Epsilon must be formatted like an ISO 8601 Duration."

I have started a job with epsilon PT1800S and retries with value 2, and during the 30mins, this worked failed every time and Chronos rescheduled this job almost every minute.

below is log from mesos:
ID	Name	State	Started	Stopped	Host	
ct:1481771185895:2:check_hdfs_mds_user_info:	ChronosTask:check_hdfs_mds_user_info	FAILED	20 minutes ago	20 minutes ago	10.77.16.104	Sandbox
ct:1481771121575:1:check_hdfs_mds_user_info:	ChronosTask:check_hdfs_mds_user_info	FAILED	21 minutes ago	21 minutes ago	10.77.16.104	Sandbox
ct:1481770860475:0:check_hdfs_mds_user_info:	ChronosTask:check_hdfs_mds_user_info	FAILED	22 minutes ago	22 minutes ago	10.77.16.104	Sandbox
ct:1481771025049:2:ods_strategy_offline_user_partition:	ChronosTask:ods_strategy_offline_user_partition	FAILED	23 minutes ago	22 minutes ago	10.77.16.104	Sandbox
ct:1481770943178:1:ods_strategy_offline_user_partition:	ChronosTask:ods_strategy_offline_user_partition	FAILED	24 minutes ago	24 minutes ago	10.77.16.104	Sandbox
ct:1481770860655:0:ods_strategy_offline_user_partition:	ChronosTask:ods_strategy_offline_user_partition	FAILED	25 minutes ago	25 minutes ago	10.77.16.104	Sandbox
ct:1481770202113:2:check_hdfs_mds_user_info:	ChronosTask:check_hdfs_mds_user_info	FAILED	36 minutes ago	36 minutes ago	10.77.16.104	Sandbox
ct:1481770135265:1:check_hdfs_mds_user_info:	ChronosTask:check_hdfs_mds_user_info	FAILED	37 minutes ago	37 minutes ago	10.77.16.104	Sandbox
ct:1481770063102:0:check_hdfs_mds_user_info:	ChronosTask:check_hdfs_mds_user_info	FAILED	39 minutes ago	38 minutes ago	10.77.16.104	Sandbox
ct:1481769912605:2:check_hdfs_mds_user_info:	ChronosTask:check_hdfs_mds_user_info	FAILED	41 minutes ago	41 minutes ago	10.77.16.104	Sandbox
ct:1481769831671:1:check_hdfs_mds_user_info:	ChronosTask:check_hdfs_mds_user_info	FAILED	42 minutes ago	42 minutes ago	10.77.16.104	Sandbox

In my view, "reties" means the totally run times and the interval between retries should be "epsilon", but it seems wrong. I got a lot of runnning logs during "epsilon" time, and the times of rerun job is bigger than "reties". So my problem is how to set "epsilon" and "retries" to control the reties times totally, thanks.

**Comment by brndnmtthws** [comment]
Epsilon can be thought of as the tolerance between the scheduled date, and the time when the scheduled checks to see if the job should be ran. If the current time is within epsilon of the scheduled date, the job will be run. If not, it will not be run.

Epsilon does not affect retry behaviour.

The concept of epsilon was removed entirely start from v3.0.0.
