### ISSUE TITLE
The job will run automatically，although the final repetition time is reached

### ISSUE THREAD

**Issue by 857851000** [mesos/chronos#776]
After fixes #772 ,I compiled the latest code of the chronos.jar package,but I found a new problem.The job will run automatically and will continue to repeat the implementation,although the final repetition time is reached.
I think this should be a bug.Can you help me solve this problem?@brndnmtthws 
Thanks!

Using the latest chronos-master code and mesos 1.1.0
The following is my job JSON file:

{

  "name": "chronostest",
  "command": "for i in `seq 1 10`;do echo \\\"Hello, Welcome $i times\\\";sleep 2;done",
  "shell": true,
  "executor": "",
  "executorFlags": "",
  "taskInfoData": "",
  "retries": 2,
  "owner": "",
  "ownerName": "",
  "description": "",
  "cpus": 0.1,
  "disk": 256,
  "mem": 128,
  "disabled": false,
  "softError": false,
  "dataProcessingJobType": false,
  "fetch": [],
  "uris": [],
  "environmentVariables": [],
  "arguments": [],
  "highPriority": false,
  "runAsUser": "root",
  "concurrent": false,
  "constraints": [],
  "schedule": "R1/2017-01-01T03:00:00.000Z/PT24H",
  "scheduleTimeZone": ""
}

![image](https://cloud.githubusercontent.com/assets/24416145/21837374/a067636e-d806-11e6-8ba0-cce6d553855f.png)

![image](https://cloud.githubusercontent.com/assets/24416145/21837417/ec23d828-d806-11e6-8209-c3fb7de80bde.png)

`03:36:34.506 [qtp707992390-33] INFO org.apache.mesos.chronos.scheduler.api.Iso8601JobResource - Received request for job:ScheduleBasedJob(R1/2017-01-01T03:00:00.000Z/PT24H,chronostest,for i in `seq 1 10`;do echo \"Hello, Welcome $i times\";sleep 2;done,0,0,,,,2,,,,,,0.1,256.0,128.0,false,0,ListBuffer(),ListBuffer(),false,root,null,,ListBuffer(),true,ListBuffer(),false,false,ListBuffer(),false)
03:36:34.565 [qtp707992390-33] INFO org.apache.mesos.chronos.scheduler.jobs.JobScheduler - Persisting job:chronostest
03:36:34.565 [qtp707992390-33] INFO org.apache.mesos.chronos.scheduler.state.MesosStatePersistenceStore - Persisting job 'chronostest' with data 'ScheduleBasedJob(R1/2017-01-01T03:00:00.000Z/PT24H,chronostest,for i in `seq 1 10`;do echo \"Hello, Welcome $i times\";sleep 2;done,0,0,,,,2,,,,,,0.1,256.0,128.0,false,0,ListBuffer(),ListBuffer(),false,root,null,,ListBuffer(),true,ListBuffer(),false,false,ListBuffer(),false)'
03:36:34.842 [qtp707992390-33] INFO org.apache.mesos.chronos.scheduler.state.MesosStatePersistenceStore - State J_chronostest does not exist yet. Adding to state
03:36:35.051 [qtp707992390-33] INFO org.apache.mesos.chronos.scheduler.state.MesosStatePersistenceStore - State update successful: true
03:36:35.051 [qtp707992390-33] INFO org.apache.mesos.chronos.scheduler.api.Iso8601JobResource - Added job to JobGraph
03:36:35.051 [qtp707992390-33] INFO mesosphere.chaos.http.ChaosRequestLog - 172.16.138.1 - - [11/Jan/2017:03:36:34 +0000] "POST //172.16.138.101:4400/v1/scheduler/iso8601 HTTP/1.1" 204 0 "http://172.16.138.101:4400/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36" 68
03:36:35.054 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.JobScheduler - Reloading jobs
03:36:35.279 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.JobScheduler - jobsToRun.size=1, jobsNotToRun.size=0
03:36:35.279 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.JobScheduler - Scheduling:chronostest
03:36:35.301 [main-SendThread(172.16.138.102:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x2598b88d2a4000c, packet:: clientPath:null serverPath:null finished:false header:: 201,12  replyHeader:: 201,4294967377,0  request:: '/chronos/state/candidate,F  response:: v{'_c_bddcb7c7-5b3d-4ac3-b2ec-576f59c8c41d-latch-0000000003,'_c_aedc4156-31fc-498a-929a-5822a6425506-latch-0000000004,'_c_f8da2e38-e2f6-481c-bacf-404b9e25039c-latch-0000000005},s{4294967332,4294967332,1484105045184,1484105045184,0,9,0,0,9,3,4294967369} 
03:36:35.302 [main-SendThread(172.16.138.102:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x2598b88d2a4000c, packet:: clientPath:null serverPath:null finished:false header:: 202,4  replyHeader:: 202,4294967377,0  request:: '/chronos/state/candidate/_c_bddcb7c7-5b3d-4ac3-b2ec-576f59c8c41d-latch-0000000003,F  response:: #737761726d30313a34343030,s{4294967365,4294967365,1484105682483,1484105682483,0,0,0,169319880768880652,12,0,4294967365} 
03:36:35.313 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.JobsObserver$ - JobNotificationObserver does not handle JobQueued(ScheduleBasedJob(R1/2017-01-01T03:00:00.000Z/PT24H,chronostest,for i in `seq 1 10`;do echo \"Hello, Welcome $i times\";sleep 2;done,0,0,,,,2,,,,,,0.1,256.0,128.0,false,0,ListBuffer(),ListBuffer(),false,root,null,,ListBuffer(),true,ListBuffer(),false,false,ListBuffer(),false),ct:1484105795293:0:chronostest:,0)
03:36:35.319 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.stats.JobStats - Updating state for job (chronostest) to queued
03:36:35.319 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.JobScheduler - Reloading jobs
03:36:35.344 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.JobScheduler - jobsToRun.size=1, jobsNotToRun.size=0
03:36:35.344 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.JobScheduler - Scheduling:chronostest
03:36:35.387 [qtp707992390-36] INFO mesosphere.chaos.http.ChaosRequestLog - 172.16.138.102 - - [11/Jan/2017:03:36:35 +0000] "GET //swarm01:4400/v1/scheduler/jobs/summary HTTP/1.1" 200 140 "http://172.16.138.102:4400/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36" 8
03:36:35.791 [Thread-34] INFO org.apache.mesos.chronos.scheduler.jobs.TaskManager - Normal priority queue contains task: ct:1484105795293:0:chronostest:
03:36:36.028 [main-SendThread(172.16.138.102:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x2598b88d2a4000c, packet:: clientPath:null serverPath:null finished:false header:: 203,12  replyHeader:: 203,4294967377,0  request:: '/chronos/state/candidate,F  response:: v{'_c_bddcb7c7-5b3d-4ac3-b2ec-576f59c8c41d-latch-0000000003,'_c_aedc4156-31fc-498a-929a-5822a6425506-latch-0000000004,'_c_f8da2e38-e2f6-481c-bacf-404b9e25039c-latch-0000000005},s{4294967332,4294967332,1484105045184,1484105045184,0,9,0,0,9,3,4294967369} 
03:36:36.031 [main-SendThread(172.16.138.102:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x2598b88d2a4000c, packet:: clientPath:null serverPath:null finished:false header:: 204,4  replyHeader:: 204,4294967377,0  request:: '/chronos/state/candidate/_c_bddcb7c7-5b3d-4ac3-b2ec-576f59c8c41d-latch-0000000003,F  response:: #737761726d30313a34343030,s{4294967365,4294967365,1484105682483,1484105682483,0,0,0,169319880768880652,12,0,4294967365} 
03:36:36.036 [qtp707992390-39] INFO mesosphere.chaos.http.ChaosRequestLog - 172.16.138.1 - - [11/Jan/2017:03:36:36 +0000] "GET //172.16.138.101:4400/v1/scheduler/jobs/summary HTTP/1.1" 200 140 "http://172.16.138.101:4400/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36" 1
03:36:36.289 [Thread-34] INFO org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework - Launching tasks from offer: id {
  value: "26a0ef44-3633-4d45-a167-e94b5075d53a-O22"
}
framework_id {
  value: "26a0ef44-3633-4d45-a167-e94b5075d53a-0001"
}
slave_id {
  value: "26a0ef44-3633-4d45-a167-e94b5075d53a-S1"
}
hostname: "172.16.138.104"
resources {
  name: "cpus"
  type: SCALAR
  scalar {
    value: 1.0
  }
  role: "*"
}
resources {
  name: "mem"
  type: SCALAR
  scalar {
    value: 340.0
  }
  role: "*"
}
resources {
  name: "disk"
  type: SCALAR
  scalar {
    value: 53730.0
  }
  role: "*"
}
resources {
  name: "ports"
  type: RANGES
  ranges {
    range {
      begin: 31000
      end: 32000
    }
  }
  role: "*"
}
url {
  scheme: "http"
  address {
    hostname: "172.16.138.104"
    ip: "172.16.138.104"
    port: 5051
  }
  path: "/slave(1)"
}
 with tasks: ArrayBuffer(name: "ChronosTask:chronostest"
task_id {
  value: "ct:1484105795293:0:chronostest:"
}
slave_id {
  value: "26a0ef44-3633-4d45-a167-e94b5075d53a-S1"
}
resources {
  name: "cpus"
  type: SCALAR
  scalar {
    value: 0.1
  }
  role: "*"
}
resources {
  name: "mem"
  type: SCALAR
  scalar {
    value: 128.0
  }
  role: "*"
}
resources {
  name: "disk"
  type: SCALAR
  scalar {
    value: 256.0
  }
  role: "*"
}
command {
  environment {
    variables {
      name: "CHRONOS_RESOURCE_DISK"
      value: "256.0"
    }
    variables {
      name: "HOST"
      value: "172.16.138.104"
    }
    variables {
      name: "CHRONOS_JOB_OWNER"
      value: ""
    }
    variables {
      name: "CHRONOS_JOB_RUN_TIME"
      value: "1484105795293"
    }
    variables {
      name: "CHRONOS_JOB_NAME"
      value: "chronostest"
    }
    variables {
      name: "CHRONOS_RESOURCE_CPU"
      value: "0.1"
    }
    variables {
      name: "mesos_task_id"
      value: "ct:1484105795293:0:chronostest:"
    }
    variables {
      name: "CHRONOS_JOB_RUN_ATTEMPT"
      value: "0"
    }
    variables {
      name: "CHRONOS_RESOURCE_MEM"
      value: "128.0"
    }
  }
  value: "for i in `seq 1 10`;do echo \\\"Hello, Welcome $i times\\\";sleep 2;done"
  user: "root"
  shell: true
}
)
03:36:36.894 [Thread-34] WARN org.apache.mesos.chronos.scheduler.jobs.JobUtils$ - Filtered job as it is no longer valid.
03:36:36.895 [Thread-34] INFO org.apache.mesos.chronos.scheduler.state.MesosStatePersistenceStore - Persisting job 'chronostest' with data 'ScheduleBasedJob(R1/2017-01-01T03:00:00.000Z/PT24H,chronostest,for i in `seq 1 10`;do echo \"Hello, Welcome $i times\";sleep 2;done,0,0,,,,2,,,,,,0.1,256.0,128.0,false,0,ListBuffer(),ListBuffer(),false,root,null,,ListBuffer(),true,ListBuffer(),false,false,ListBuffer(),false)'
03:36:36.897 [Thread-34] INFO org.apache.mesos.chronos.scheduler.state.MesosStatePersistenceStore - Key for state exists already: J_chronostest
03:36:36.904 [Thread-34] INFO org.apache.mesos.chronos.scheduler.state.MesosStatePersistenceStore - State update successful: true
03:36:36.904 [Thread-34] INFO org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework - Task 'ct:1484105795293:0:chronostest:' launched
03:36:36.904 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.JobScheduler - Reloading jobs
03:36:37.186 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.JobScheduler - jobsToRun.size=1, jobsNotToRun.size=0
03:36:37.186 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.JobScheduler - Scheduling:chronostest
03:36:37.187 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.JobsObserver$ - JobNotificationObserver does not handle JobQueued(ScheduleBasedJob(R1/2017-01-01T03:00:00.000Z/PT24H,chronostest,for i in `seq 1 10`;do echo \"Hello, Welcome $i times\";sleep 2;done,0,0,,,,2,,,,,,0.1,256.0,128.0,false,0,ListBuffer(),ListBuffer(),false,root,null,,ListBuffer(),true,ListBuffer(),false,false,ListBuffer(),false),ct:1484105797186:0:chronostest:,0)
03:36:37.187 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.stats.JobStats - Updating state for job (chronostest) to queued
03:36:37.187 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.JobScheduler - Reloading jobs
03:36:37.191 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.JobScheduler - jobsToRun.size=1, jobsNotToRun.size=0
03:36:37.191 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.JobScheduler - Scheduling:chronostest
03:36:37.299 [main-SendThread(172.16.138.102:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x2598b88d2a4000c, packet:: clientPath:null serverPath:null finished:false header:: 205,12  replyHeader:: 205,4294967378,0  request:: '/chronos/state/candidate,F  response:: v{'_c_bddcb7c7-5b3d-4ac3-b2ec-576f59c8c41d-latch-0000000003,'_c_aedc4156-31fc-498a-929a-5822a6425506-latch-0000000004,'_c_f8da2e38-e2f6-481c-bacf-404b9e25039c-latch-0000000005},s{4294967332,4294967332,1484105045184,1484105045184,0,9,0,0,9,3,4294967369} 
03:36:37.301 [main-SendThread(172.16.138.102:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x2598b88d2a4000c, packet:: clientPath:null serverPath:null finished:false header:: 206,4  replyHeader:: 206,4294967378,0  request:: '/chronos/state/candidate/_c_bddcb7c7-5b3d-4ac3-b2ec-576f59c8c41d-latch-0000000003,F  response:: #737761726d30313a34343030,s{4294967365,4294967365,1484105682483,1484105682483,0,0,0,169319880768880652,12,0,4294967365} 
03:36:37.303 [qtp707992390-40] INFO mesosphere.chaos.http.ChaosRequestLog - 172.16.138.102 - - [11/Jan/2017:03:36:37 +0000] "GET //swarm01:4400/v1/scheduler/jobs/summary HTTP/1.1" 200 140 "http://172.16.138.102:4400/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36" 
03:36:38.021 [main-SendThread(172.16.138.102:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x2598b88d2a4000c, packet:: clientPath:null serverPath:null finished:false header:: 207,12  replyHeader:: 207,4294967378,0  request:: '/chronos/state/candidate,F  response:: v{'_c_bddcb7c7-5b3d-4ac3-b2ec-576f59c8c41d-latch-0000000003,'_c_aedc4156-31fc-498a-929a-5822a6425506-latch-0000000004,'_c_f8da2e38-e2f6-481c-bacf-404b9e25039c-latch-0000000005},s{4294967332,4294967332,1484105045184,1484105045184,0,9,0,0,9,3,4294967369} 
03:36:38.023 [main-SendThread(172.16.138.102:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x2598b88d2a4000c, packet:: clientPath:null serverPath:null finished:false header:: 208,4  replyHeader:: 208,4294967378,0  request:: '/chronos/state/candidate/_c_bddcb7c7-5b3d-4ac3-b2ec-576f59c8c41d-latch-0000000003,F  response:: #737761726d30313a34343030,s{4294967365,4294967365,1484105682483,1484105682483,0,0,0,169319880768880652,12,0,4294967365} 
03:36:38.029 [qtp707992390-35] INFO mesosphere.chaos.http.ChaosRequestLog - 172.16.138.1 - - [11/Jan/2017:03:36:38 +0000] "GET //172.16.138.101:4400/v1/scheduler/jobs/summary HTTP/1.1" 200 140 "http://172.16.138.101:4400/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36" 
03:36:38.406 [Thread-35] INFO org.apache.mesos.chronos.scheduler.jobs.JobsObserver$ - JobNotificationObserver does not handle JobStarted(ScheduleBasedJob(R1/2017-01-01T03:00:00.000Z/PT24H,chronostest,for i in `seq 1 10`;do echo \"Hello, Welcome $i times\";sleep 2;done,0,0,,,,2,,,,,,0.1,256.0,128.0,false,0,ListBuffer(),ListBuffer(),false,root,null,,ListBuffer(),true,ListBuffer(),false,false,ListBuffer(),false),task_id {
  value: "ct:1484105795293:0:chronostest:"
}
state: TASK_RUNNING
slave_id {
  value: "26a0ef44-3633-4d45-a167-e94b5075d53a-S1"
}
timestamp: 1.484105797485429E9
executor_id {
  value: "ct:1484105795293:0:chronostest:"
}
source: SOURCE_EXECUTOR
uuid: "\340oM~+tL\323\206\333(\211\373\367\031*"
container_status {
  network_infos {
    ip_addresses {
      ip_address: "172.16.138.104"
    }
  }
  executor_pid: 35
}
,0,1)
03:36:38.408 [Thread-35] INFO org.apache.mesos.chronos.scheduler.jobs.stats.JobStats - Updating state for job (chronostest) to running
03:36:38.419 [Thread-35] INFO org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework - Task with id 'ct:1484105795293:0:chronostest:' RUNNING
03:36:39.301 [main-SendThread(172.16.138.102:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x2598b88d2a4000c, packet:: clientPath:null serverPath:null finished:false header:: 209,12  replyHeader:: 209,4294967378,0  request:: '/chronos/state/candidate,F  response:: v{'_c_bddcb7c7-5b3d-4ac3-b2ec-576f59c8c41d-latch-0000000003,'_c_aedc4156-31fc-498a-929a-5822a6425506-latch-0000000004,'_c_f8da2e38-e2f6-481c-bacf-404b9e25039c-latch-0000000005},s{4294967332,4294967332,1484105045184,1484105045184,0,9,0,0,9,3,4294967369} 
03:36:39.303 [main-SendThread(172.16.138.102:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x2598b88d2a4000c, packet:: clientPath:null serverPath:null finished:false header:: 210,4  replyHeader:: 210,4294967378,0  request:: '/chronos/state/candidate/_c_bddcb7c7-5b3d-4ac3-b2ec-576f59c8c41d-latch-0000000003,F  response:: #737761726d30313a34343030,s{4294967365,4294967365,1484105682483,1484105682483,0,0,0,169319880768880652,12,0,4294967365} 
03:36:39.306 [qtp707992390-59] INFO mesosphere.chaos.http.ChaosRequestLog - 172.16.138.102 - - [11/Jan/2017:03:36:39 +0000] "GET //swarm01:4400/v1/scheduler/jobs/summary HTTP/1.1" 200 143 "http://172.16.138.102:4400/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36" 
03:36:40.221 [main-SendThread(172.16.138.102:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x2598b88d2a4000c, packet:: clientPath:null serverPath:null finished:false header:: 211,12  replyHeader:: 211,4294967378,0  request:: '/chronos/state/candidate,F  response:: v{'_c_bddcb7c7-5b3d-4ac3-b2ec-576f59c8c41d-latch-0000000003,'_c_aedc4156-31fc-498a-929a-5822a6425506-latch-0000000004,'_c_f8da2e38-e2f6-481c-bacf-404b9e25039c-latch-0000000005},s{4294967332,4294967332,1484105045184,1484105045184,0,9,0,0,9,3,4294967369} 
03:36:40.225 [main-SendThread(172.16.138.102:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x2598b88d2a4000c, packet:: clientPath:null serverPath:null finished:false header:: 212,4  replyHeader:: 212,4294967378,0  request:: '/chronos/state/candidate/_c_bddcb7c7-5b3d-4ac3-b2ec-576f59c8c41d-latch-0000000003,F  response:: #737761726d30313a34343030,s{4294967365,4294967365,1484105682483,1484105682483,0,0,0,169319880768880652,12,0,4294967365} 
03:36:40.227 [qtp707992390-37] INFO mesosphere.chaos.http.ChaosRequestLog - 172.16.138.1 - - [11/Jan/2017:03:36:40 +0000] "GET //172.16.138.101:4400/v1/scheduler/jobs/summary HTTP/1.1" 200 143 "http://172.16.138.101:4400/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36" 
03:36:41.302 [main-SendThread(172.16.138.102:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x2598b88d2a4000c, packet:: clientPath:null serverPath:null finished:false header:: 213,12  replyHeader:: 213,4294967378,0  request:: '/chronos/state/candidate,F  response:: v{'_c_bddcb7c7-5b3d-4ac3-b2ec-576f59c8c41d-latch-0000000003,'_c_aedc4156-31fc-498a-929a-5822a6425506-latch-0000000004,'_c_f8da2e38-e2f6-481c-bacf-404b9e25039c-latch-0000000005},s{4294967332,4294967332,1484105045184,1484105045184,0,9,0,0,9,3,4294967369} 
03:36:41.310 [main-SendThread(172.16.138.102:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x2598b88d2a4000c, packet:: clientPath:null serverPath:null finished:false header:: 214,4  replyHeader:: 214,4294967378,0  request:: '/chronos/state/candidate/_c_bddcb7c7-5b3d-4ac3-b2ec-576f59c8c41d-latch-0000000003,F  response:: #737761726d30313a34343030,s{4294967365,4294967365,1484105682483,1484105682483,0,0,0,169319880768880652,12,0,4294967365} 
03:36:41.314 [qtp707992390-33] INFO mesosphere.chaos.http.ChaosRequestLog - 172.16.138.102 - - [11/Jan/2017:03:36:41 +0000] "GET //swarm01:4400/v1/scheduler/jobs/summary HTTP/1.1" 200 143 "http://172.16.138.102:4400/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36" 1
03:36:42.802 [Thread-36] INFO org.apache.mesos.chronos.scheduler.jobs.TaskManager - Normal priority queue contains task: ct:1484105797186:0:chronostest:
03:36:42.802 [Thread-36] WARN org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework - The head of the task queue appears to already be running and doesn't allow concurrency: chronostest`

**Comment by brndnmtthws** [comment]
This should be fixed by #789 and #790.
