### ISSUE TITLE
Is there any way to migrate all the Chronos from One to another Server?

### ISSUE THREAD

**Issue by batizty** [mesos/chronos#782]
I have deployed 10.77.xx.1 as Chronos Server, and it works well as our team task scheduler.

But later, I need to migrate this Chronos from 10.77.xx.1 to another more powerful machine, and i could not find like db or other persistence files to store all the tasks.

Is there any way to do this kind of migratation work?

And i am using Chronos 2.4.0.0 and i have made some little modifies like 

1. support crontab work translation
2. After all parents tasks finished, the children will be scheduled

But i am not sure these works have been fixed, so any one have finished these work, i am interested in to discuss.

Thanks

**Comment by rdigiorgio** [comment]
As documentation states:

    -z, --zk_hosts  <arg>         The list of ZooKeeper servers for storing state
    --zk_path  <arg>                Path in ZooKeeper for storing state

Chronos state is stored in your Zookeeper cluster, at specified path (chronos by default, I guess). You just have to start Chronos on the new machine, using the same ZK cluster.

About migration from version 2.4.0, I can't help you. :)

**Comment by batizty** [comment]
Thank you very much, as you mentioned that on zookeeper root path, there is an path named chronos with all jobs and running tasks information. And nice tool for me and my team, I am using it manage all hive and hadoop work now.

👍
