### ISSUE TITLE
Async jobs on chronos 2.4 not working

### ISSUE THREAD

**Issue by abhishekdeshpande** [mesos/chronos#783]
We are seeing a weird issue on Chronos 2.4.0. We are setting up Async as true. If we don't report the completion status for the job, the chronos UI shows it as 'running' which works as expected but Mesos keeps triggering the job even when we haven't sent the callback. 

Ideally it should wait for the callback and not trigger the job. Chronos does the work but Mesos isn't respecting Chronos. Can somebody help with this? 

Is there an executor that i might be missing that is causing this issue?

**Comment by brndnmtthws** [comment]
Async jobs have been removed starting from 3.0.0, and I'm not going to fix it in <3.0.0.
