### ISSUE TITLE
UI prevents enter docker image that includes registry server

### ISSUE THREAD

**Issue by mindscratch** [mesos/chronos#785]
**Version:** Chronos 3.0.0

If I try to create a new job through the UI which has a Container Image value like `myregistry.foobar.internal/centos`  ...the UI flags it as invalid and displays an error `Container Image must match regex /^[a-z0-9/:]+$/`

I believe updating regex to allow periods will fix the issue.

**Workaround:** create the job by using the HTTP API

**Comment by liangyanfeng** [comment]
UI prevents enter docker image that includes  -_ 

I think we should use /^[-_a-z0-9\/\.:]+$/  instead of /^[a-z0-9\/\.:]+$/

**Comment by brndnmtthws** [comment]
Thanks, noted!

**Comment by asyd** [comment]
Hi, any update to allow / (to allow repository?) 

And btw why upper letters are not allowed?

**Comment by asyd** [comment]
Hi, 

is there a particular reason that uppercase letters are not allowed?
