### ISSUE TITLE
schedule parameter using hour fail

### ISSUE THREAD

**Issue by robsonpeixoto** [mesos/chronos#798]
I'm trying to configure a job with the schedule: `"schedule": "R/2017-01-25T07:00:00-03:00/P1H"` but fails.

When I change from `.../P1H` to `.../P1D` it works.

I'm using the version `2.4.0`

**Comment by brndnmtthws** [comment]
This is a quirk of the ISO8601 spec. If you want to specify a time (like, 1h), you need a **T** in the period, like `PT1H`.
