### ISSUE TITLE
Chronos response becomes very slow when there are a lot of tasks

### ISSUE THREAD

**Issue by 857851000** [mesos/chronos#803]
We use Chronos to schedule more than 1000+ tasks, and as the number of tasks increases, we find that Chronos has a very long response time when modifying, deleting, and adding tasks.By looking at the Chronos log, we can found a large number of same logs:

`08:49:59.152 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.JobScheduler - Reloading jobs
08:49:59.590 [pool-4-thread-1] INFO org.apache.mesos.chronos.scheduler.jobs.JobScheduler - jobsToRun.size=1, jobsNotToRun.size=1001`

In Chronos source code file `JobScheduler`, there is an infinite loop function `mainLoop ()`,we tried to add sleep to reduce the cycle interval and found that the Chronos response time was greatly reduced. So can you consider adding a parameter to control the sleep time length according to the actual application needs,or give other better solutions.

In addition, when there are a large number of tasks Chronos Web page open time is very long or can not open.

Chronos version:3.0.1
Mesos version:1.1.0

**Comment by brndnmtthws** [comment]
What exactly did you change in the code to improve Chronos? What's the period of your jobs? Chronos should 'go to sleep' unless there's something to schedule.

**Comment by 857851000** [comment]
By looking at the source code `JobScheduler`,we think `condition.awaitNanos (nanos)` should let Chronos wait for task scheduling at first,but it seems not work.So we force to add sleep at the beginning of the loop,the specific location is as follows:
![image](https://cloud.githubusercontent.com/assets/24416145/23049054/975a31ba-f4f4-11e6-8664-f7b6be21cacf.png)
Most the period of our jobs are 1 hour and 24 hours.

**Comment by brndnmtthws** [comment]
Can you run a test and print the values of `conditionNotified.get()` and `nanos` in that context? Also maybe print a log message every time `notifyCondition()` is called to see if that's the problem.

**Comment by brndnmtthws** [comment]
Ah, okay, I see a potential edge case. Let me throw up a patch, and hopefully it fixes it for you.

**Comment by brndnmtthws** [comment]
I'm not sure if that patch will work, so reopen this if it does not.
