### ISSUE TITLE
Prevent job to run immediately if only the time is configured

### ISSUE THREAD

**Issue by elisiariocouto** [mesos/chronos#807]
Hello,
We're giving Chronos a try for our daily batch jobs. We tried both configurations for the `schedule` field:
 1. `R/2017-02-24T05:50Z/PT24H`
 2. `R/T05:50Z/PT24H`

If I create the second version of the job, Chronos edits my `schedule` field and completes it with a full-ISO8601 version of it, which is correct but it runs the job right away.

How can I submit a daily job with only hours configured and prevent it from running immediately?

**Comment by brndnmtthws** [comment]
I don't think it's possible to do what you're trying to do. You could just set the start date to some point in the future, if that's your goal.

**Comment by elisiariocouto** [comment]
Let's say that right now is `2017-02-24 10:30`, if I submit a job with a date in the future (let's say `2017-02-24 11:00`), the job does not run right away, it waits half an hour which is correct. But if I omit the date part and submit the job (`11:00`), the final job description that chronos shows me on the Web UI is correct (`2017-02-24 11:00`) but the job runs immediately.

Isn't this a bug?

**Comment by brndnmtthws** [comment]
No I don't think so. It sounds like a bug that the UI accepts that as valid
input. The date needs to conform to the ISO8601 spec.

**Comment by elisiariocouto** [comment]
Ok. Just clear things out, I've used the HTTP API to submit the jobs.

**Comment by renou** [comment]
@elisiariocouto @brndnmtthws Any luck with getting around this issue? I have a pipeline that creates multiple chronos jobs on deployment time, and after the job got created, they all get kicked off at the same time and it is troublesome... 😢  Thank you in advance!

**Comment by elisiariocouto** [comment]
Workaround is creating a full ISO9601 date in the future I think...

**Comment by renou** [comment]
haha Thanks! @elisiariocouto

**Comment by renou** [comment]
@brndnmtthws Do you know how most people dealt with this issue? feels like a feature to add?
