### ISSUE TITLE
What version of Chronos should I use?

### ISSUE THREAD

**Issue by edi33416** [mesos/chronos#877]
Hello everyone,

I am building Chronos from source and I was wondering what is the recommended Chronos version to use?
Should I use `2.5.1` branch or the `master` branch?

I understand that 3.x is no longer supported, but I've seen that v3.x introduce the `output_file` argument for the fetcher, which is not available in 2.5.1.

Are the bug fixes applied to 2.5.x versions or not?
Any reason not to use the `master` branch?

I posted the same question on the google-groups [forum](https://groups.google.com/forum/#!topic/chronos-scheduler/OuXqgRQh4_g), but nobody replied.

Kind regards,
Eduard

**Comment by edi33416** [comment]
@brndnmtthws @gkleiman Could you please help me with a suggestion?

**Comment by brndnmtthws** [comment]
@edi33416 I don't know the status of the project, but my guess is that nobody is actively working on it anymore.

**Comment by gkleiman** [comment]
@edi33416 Chronos 2.x is still on life support, and regularly tested on DC/OS. I do my best effort to review/merge PRs against 2.x

Nobody is actively working on Chronos 3.x.

**Comment by edi33416** [comment]
@gkleiman any reason why I should not use the `master` branch and use the `2.5.1` tag?
I'm asking this because it looks like `2.5.1` doesn't have all the master commits: i.e. the `output_file` fetcher argument is not available.

@brndnmtthws @gkleiman Are there any alternatives to Chronos for a Mesos Cluster?
I've been looking around and I haven't found an alternative:

- Airflow has a very basic support for Mesos: can't dynamically specify the amount of required resources per job; the amount of resources seems to be hard-coded in the config file for the `MesosExecutor`
- Marathon does not support one off jobs
- Aurora, Metronome and Singularity don't have DAG support
- I know the guys at Twitter are using an Airflow + Aurora stack, but I can't do that as I need to be able to also run jobs on Windows Agents

**Comment by gkleiman** [comment]
@edi33416 the 2.5.x releases are built from the `stable` branch, the `master` branch is used for 3.x.

I am not aware of any alternatives with DAG support for Mesos clusters.
