### ISSUE TITLE
How to use the `taskInfoData` job field

### ISSUE THREAD

**Issue by edi33416** [mesos/chronos#880]
I am trying to specify a max run time for a job, and I think this could be done by setting the `DurationInfo` in [TaskInfo](https://github.com/apache/mesos/blob/master/include/mesos/mesos.proto#L2137)

From the Chronos [docs](), it is unclear to me how I can use the `taskInfoData` field to achieve my goal.

Could someone please provide me with an example?

Thank you,
Eduard

**Comment by edi33416** [comment]
@gkleiman @brndnmtthws Sorry for the  spam guys, but could you please help me?

**Comment by gkleiman** [comment]
@edi33416 the job's `taskInfoData` field is used by Chronos to populate `ExecutorInfo.data`, so it can't be used to change the max run time.

You would have to write a patch to add a new field to Chronos jobs and make Chronos use it to populate `TaskInfo.max_completion_time` when launching a task.

**Comment by edi33416** [comment]
@gkleiman I created the #881 PR for this issue

**Comment by edi33416** [comment]
Closing as this has been implemented in #881
